## Numero de viviendas y de plazas turísticas 2020
En este notebook procesaremos un JSON que contiene, para cada municipio, el número de viviendas y plazas turísticas en el año 2020.  
Obtendremos dos DataFrame con la siguiente información común:
- Y2020
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio

Y en cada uno de de los DataFrame, uno de los siguientes campos:
- Nº Viviendas Turisticas
- Nº Plazas Turísiticas

In [1]:
import pandas as pd
import requests

In [2]:
path = 'https://servicios.ine.es/wstempus/js/es/DATOS_TABLA/39363?tip=AM&'
json_request = requests.get(path).json()

In [3]:
CodVivList = list()
NumVivList = list()
CodPlaList = list()
NumPlaList = list()

In [4]:
for dato in json_request: 
    for i in range(0,len(dato['Data'])):
        if 'Viviendas turísticas' in dato['Nombre'] and dato['Data'][i]['Anyo'] == 2020:
            CodVivList.append(dato['MetaData'][0]['Codigo'])
            NumVivList.append(dato['Data'][i]['Valor'])
        elif 'Plazas. Dato base' in dato['Nombre'] and dato['Data'][i]['Anyo'] == 2020:
            CodPlaList.append(dato['MetaData'][0]['Codigo'])
            NumPlaList.append(dato['Data'][i]['Valor'])

In [5]:
ViviendasTuristicas20 = pd.DataFrame({
        'Codigo Municipio' : CodVivList,
        'Nº Viviendas Turisticas': NumVivList
    })
PlazasTuristicas20 = pd.DataFrame({
        'Codigo Municipio' : CodPlaList,
        'Nº Plazas Turisticas': NumPlaList
    })

In [6]:
ViviendasTuristicas20.head()

  Codigo Municipio  Nº Viviendas Turisticas
0               00                 321496.0
1               01                  67392.0
2               02                   3767.0
3               03                   4891.0
4               04                  29237.0

In [7]:
PlazasTuristicas20.head()

  Codigo Municipio  Nº Plazas Turisticas
0               00             1627377.0
1               01              340256.0
2               02               20167.0
3               03               24698.0
4               04              182748.0

Cargamos la tabla 01_Output_ProvMun_20.xlsx para posteriormente realizar el merge con las tablas anteriores:

In [8]:
ProvMun = pd.read_excel('01_Output_ProvMun_20.xlsx', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

In [9]:
ViviendasTuristicas20 = ProvMun.merge(ViviendasTuristicas20, on='Codigo Municipio')
PlazasTuristicas20 = ProvMun.merge(PlazasTuristicas20 , on='Codigo Municipio')

Añadimos una columna con el año 2020:

In [10]:
ViviendasTuristicas20['Y2020'] = 2020
PrimeraColumna = ViviendasTuristicas20.pop('Y2020')
ViviendasTuristicas20.insert(0,'Y2020', PrimeraColumna)
ViviendasTuristicas20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Nº Viviendas Turisticas
0,2020,Araba/Álava,01,Agurain/Salvatierra,01051,2.0
1,2020,Araba/Álava,01,Alegría-Dulantzi,01001,2.0
2,2020,Araba/Álava,01,Amurrio,01002,8.0
3,2020,Araba/Álava,01,Añana,01049,4.0
4,2020,Araba/Álava,01,Aramaio,01003,0.0

In [11]:
PlazasTuristicas20['Y2020'] = 2020
PrimeraColumna = PlazasTuristicas20.pop('Y2020')
PlazasTuristicas20.insert(0,'Y2020', PrimeraColumna)
PlazasTuristicas20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Nº Plazas Turisticas
0,2020,Araba/Álava,01,Agurain/Salvatierra,01051,8.0
1,2020,Araba/Álava,01,Alegría-Dulantzi,01001,11.0
2,2020,Araba/Álava,01,Amurrio,01002,56.0
3,2020,Araba/Álava,01,Añana,01049,41.0
4,2020,Araba/Álava,01,Aramaio,01003,0.0

In [12]:
ViviendasTuristicas20.to_excel('16_Output_Viviendas_Turisticas_20.xlsx', header = True, index = False)
PlazasTuristicas20.to_excel('16_Output_Plazas_Turisticas_20.xlsx', header = True, index = False)