In [1]:
import pandas as pd

In [38]:
Densidad11 = pd.read_csv('Data/03_Output_Densidad_Poblacion_11.csv' ,dtype='object')

In [39]:
Densidad21 = pd.read_csv('Data/03_Output_Densidad_Poblacion_21.csv' ,dtype='object')

In [40]:
Densidad11.head()

  Codigo Municipio Superficie Km2 Densidad Poblacion
0            01001          19.95              140.5
1            01002           96.3             103.99
2            01003          73.02              20.49
3            01004          27.29              67.53
4            01006          12.97              17.66

In [41]:
Densidad21.head()

  Codigo Municipio Superficie Km2 Densidad Poblacion
0            01001          19.95             146.62
1            01002           96.3             107.03
2            01003          73.02              19.94
3            01004          27.29              66.29
4            01006          12.97              17.81

In [42]:
Densidad11['Densidad Poblacion'] = Densidad11['Densidad Poblacion'].astype('float64')
Densidad21['Densidad Poblacion'] = Densidad21['Densidad Poblacion'].astype('float64')

In [43]:
Densidad11['UmbralDesp'] = Densidad11['Densidad Poblacion'].map(lambda x: 'Despoblado' if x <= 12.5 else 'Poblado')
Densidad21['UmbralDesp'] = Densidad21['Densidad Poblacion'].map(lambda x: 'Despoblado' if x <= 12.5 else 'Poblado')

In [36]:
Densidad11['Umbral Despoblacion'].value_counts()

Poblado       4410
Despoblado    3706
Name: Umbral Despoblacion, dtype: int64

In [37]:
Densidad21['Umbral Despoblacion'].value_counts()

Poblado       4183
Despoblado    3948
Name: Umbral Despoblacion, dtype: int64

In [ ]:
## preparamos un dataframe para el mapa
# cogemos el mapa de 2021 y