## Densidad población 2020 y 2010

En este notebook procesaremos un .xlsx con la superficie de cada uno de los municipios: 03_Input_Densidad_Poblacion_10_20.xlsx

In [1]:
import pandas as pd
import numpy as np

In [2]:
DensidadPoblacion = pd.read_excel('03_Input_Densidad_Poblacion_10_20.xlsx', dtype='object', usecols=('ID_REL',
                                        'PROVINCIA',
                                        'NOMBRE_ACTUAL', 'SUPERFICIE'))

In [3]:
DensidadPoblacion.head()

  ID_REL    PROVINCIA     NOMBRE_ACTUAL SUPERFICIE
0  01001  Araba/Álava  Alegría-Dulantzi  1994.5872
1  01002  Araba/Álava           Amurrio    9629.68
2  01003  Araba/Álava           Aramaio     7302.1
3  01004  Araba/Álava        Artziniega    2728.73
4  01006  Araba/Álava           Armiñón    1297.27

In [4]:
DensidadPoblacion.rename({'ID_REL': 'Codigo Municipio'}, axis=1, inplace=True)

### Densidad población 2020

Junto con la tabla 02_Output_Poblacion20.xlsx que contiene la población de 2020, obtendremos un Dataframe 
con la siguiente información:
- Y2020
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio
- Poblacion Total
- Superficie km2
- Densidad Población

In [5]:
Poblacion20 = pd.read_excel('02_Output_Poblacion20.xlsx',dtype='object', usecols=('Y2020',
                                                                                  'Nombre Provincia',
                                                                                  'Codigo Provincia',
                                                                                  'Nombre Municipio', 
                                                                                  'Codigo Municipio', 
                                                                                  'Poblacion Total'))
Poblacion20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Poblacion Total
0,2020,Araba/Álava,01,Alegría-Dulantzi,01001,2935
1,2020,Araba/Álava,01,Amurrio,01002,10264
2,2020,Araba/Álava,01,Añana,01049,149
3,2020,Araba/Álava,01,Aramaio,01003,1442
4,2020,Araba/Álava,01,Armiñón,01006,223

In [6]:
DensidadPoblacion20 = DensidadPoblacion.merge(Poblacion20, on='Codigo Municipio')
DensidadPoblacion20.head()

,Codigo Municipio,PROVINCIA,NOMBRE_ACTUAL,SUPERFICIE,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Poblacion Total
0,01001,Araba/Álava,Alegría-Dulantzi,1994.5872,2020,Araba/Álava,01,Alegría-Dulantzi,2935
1,01002,Araba/Álava,Amurrio,9629.68,2020,Araba/Álava,01,Amurrio,10264
2,01003,Araba/Álava,Aramaio,7302.1,2020,Araba/Álava,01,Aramaio,1442
3,01004,Araba/Álava,Artziniega,2728.73,2020,Araba/Álava,01,Artziniega,1800
4,01006,Araba/Álava,Armiñón,1297.27,2020,Araba/Álava,01,Armiñón,223

In [7]:
DensidadPoblacion20 = DensidadPoblacion20.drop(['PROVINCIA', 'NOMBRE_ACTUAL'],axis=1)

La superficie está en hectareas, la pasamos a km2 y calculamos la densidad:

In [8]:
DensidadPoblacion20.dtypes

Codigo Municipio    object
SUPERFICIE          object
Y2020               object
Nombre Provincia    object
Codigo Provincia    object
Nombre Municipio    object
Poblacion Total     object
dtype: object

In [9]:
DensidadPoblacion20['SUPERFICIE'] = DensidadPoblacion20['SUPERFICIE'].astype(float).round(2)
DensidadPoblacion20['Poblacion Total'] = DensidadPoblacion20['Poblacion Total'].astype(float).round(2)

DensidadPoblacion20['Superficie Km2'] = DensidadPoblacion20['SUPERFICIE'].map(lambda x: x/100).round(2)
DensidadPoblacion20['Densidad Poblacion'] = (DensidadPoblacion20['Poblacion Total'] / DensidadPoblacion20['Superficie Km2']).round(2)

In [10]:
ColNue = ['Y2020','Nombre Provincia', 'Codigo Provincia', 'Nombre Municipio','Codigo Municipio',
          'Poblacion Total', 'Superficie Km2', 'Densidad Poblacion']
DensidadPoblacion20 = DensidadPoblacion20[ColNue]

In [11]:
DensidadPoblacion20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Poblacion Total,Superficie Km2,Densidad Poblacion
0,2020,Araba/Álava,01,Alegría-Dulantzi,01001,2935.0,19.95,147.12
1,2020,Araba/Álava,01,Amurrio,01002,10264.0,96.30,106.58
2,2020,Araba/Álava,01,Aramaio,01003,1442.0,73.02,19.75
3,2020,Araba/Álava,01,Artziniega,01004,1800.0,27.29,65.96
4,2020,Araba/Álava,01,Armiñón,01006,223.0,12.97,17.19

In [12]:
DensidadPoblacion20.to_excel('03_Output_Densidad_Poblacion_20.xlsx', header = True, index = False)

### Densidad población 2010

Junto con la tabla 02_Output_Poblacion10.xlsx que contiene la población de 2010, obtendremos un Dataframe 
con la siguiente información:
- Y2010
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio
- Poblacion Total
- Superficie_km2
- Densidad Población

In [13]:
Poblacion10 = pd.read_excel('02_Output_Poblacion10.xlsx',dtype='object', usecols=('Y2010',
                                                                                  'Nombre Provincia',
                                                                                  'Codigo Provincia',
                                                                                  'Nombre Municipio', 
                                                                                  'Codigo Municipio', 
                                                                                  'Poblacion Total'))
Poblacion10.head()

,Y2010,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Poblacion Total
0,2010,Araba/Álava,01,Alegría-Dulantzi,01001,2714
1,2010,Araba/Álava,01,Amurrio,01002,10050
2,2010,Araba/Álava,01,Añana,01049,175
3,2010,Araba/Álava,01,Aramaio,01003,1497
4,2010,Araba/Álava,01,Armiñón,01006,225

En la tabla DensidadPoblacion faltan los municipios de Cerdedo, Cotobade, Cesuras y Oza dos ríos.  
Son municipios que desde 2013 y 2016 han pasado a ser dos municipios: Cesuras-Oza dos ríos y Cercedo-Cotobade.   
Los incluimos:

In [14]:
NueFil = [{'Codigo Municipio': '36011', 'PROVINCIA': 'Pontevedra', 'NOMBRE_ACTUAL': 'Cerdedo', 'SUPERFICIE': '7984' }, 
          {'Codigo Municipio': '36012', 'PROVINCIA': 'Pontevedra', 'NOMBRE_ACTUAL': 'Cotobade', 'SUPERFICIE': '13468'}, 
         {'Codigo Municipio': '15026', 'PROVINCIA': 'Coruña, A', 'NOMBRE_ACTUAL': 'Cesuras', 'SUPERFICIE': '7946'}, 
         {'Codigo Municipio': '15063', 'PROVINCIA': 'Coruña, A', 'NOMBRE_ACTUAL': 'Oza dos Ríos', 'SUPERFICIE': '7214'}]

In [15]:
DensidadPoblacion10 = DensidadPoblacion.append(NueFil, ignore_index = True)

In [16]:
DensidadPoblacion10 = DensidadPoblacion10.merge(Poblacion10, on='Codigo Municipio')
DensidadPoblacion10.head()

,Codigo Municipio,PROVINCIA,NOMBRE_ACTUAL,SUPERFICIE,Y2010,Nombre Provincia,Codigo Provincia,Nombre Municipio,Poblacion Total
0,01001,Araba/Álava,Alegría-Dulantzi,1994.5872,2010,Araba/Álava,01,Alegría-Dulantzi,2714
1,01002,Araba/Álava,Amurrio,9629.68,2010,Araba/Álava,01,Amurrio,10050
2,01003,Araba/Álava,Aramaio,7302.1,2010,Araba/Álava,01,Aramaio,1497
3,01004,Araba/Álava,Artziniega,2728.73,2010,Araba/Álava,01,Artziniega,1818
4,01006,Araba/Álava,Armiñón,1297.27,2010,Araba/Álava,01,Armiñón,225

In [17]:
DensidadPoblacion10 = DensidadPoblacion10.drop(['PROVINCIA', 'NOMBRE_ACTUAL'],axis=1)

La superficie está en hectareas, la pasamos a km2 y calculamos la densidad:

In [18]:
DensidadPoblacion10['SUPERFICIE'] = DensidadPoblacion10['SUPERFICIE'].astype(float).round(2)
DensidadPoblacion10['Poblacion Total'] = DensidadPoblacion10['Poblacion Total'].astype(float).round(2)

DensidadPoblacion10['Superficie Km2'] = DensidadPoblacion10['SUPERFICIE'].map(lambda x: x/100).round(2)
DensidadPoblacion10['Densidad Poblacion'] = (DensidadPoblacion10['Poblacion Total'] / DensidadPoblacion10['Superficie Km2']).round(2)

In [19]:
ColNue = ['Y2010','Nombre Provincia', 'Codigo Provincia', 'Nombre Municipio','Codigo Municipio',
          'Poblacion Total', 'Superficie Km2', 'Densidad Poblacion']
DensidadPoblacion10 = DensidadPoblacion10[ColNue]

In [20]:
DensidadPoblacion10.head()

,Y2010,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Poblacion Total,Superficie Km2,Densidad Poblacion
0,2010,Araba/Álava,01,Alegría-Dulantzi,01001,2714.0,19.95,136.04
1,2010,Araba/Álava,01,Amurrio,01002,10050.0,96.30,104.36
2,2010,Araba/Álava,01,Aramaio,01003,1497.0,73.02,20.50
3,2010,Araba/Álava,01,Artziniega,01004,1818.0,27.29,66.62
4,2010,Araba/Álava,01,Armiñón,01006,225.0,12.97,17.35

In [21]:
DensidadPoblacion10.to_excel('03_Output_Densidad_Poblacion_10.xlsx', header = True, index = False)