## Altitud municipios

En este notebook procesaremos el archivo 03_Input_Densidad_Poblacion_10_20.xlsx para extraer la variable altitud de los municipios.  
Obtendremos un Dataframe con la siguiente información:
- Y2020
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio
- Altitud

In [1]:
import pandas as pd
import numpy as np

In [2]:
DensidadPoblacion = pd.read_excel('03_Input_Densidad_Poblacion_10_20.xlsx', dtype='object', usecols=('ID_REL',
                                        'PROVINCIA',
                                        'NOMBRE_ACTUAL', 'ALTITUD'))

In [3]:
DensidadPoblacion.head()

  ID_REL    PROVINCIA     NOMBRE_ACTUAL ALTITUD
0  01001  Araba/Álava  Alegría-Dulantzi     568
1  01002  Araba/Álava           Amurrio     219
2  01003  Araba/Álava           Aramaio     333
3  01004  Araba/Álava        Artziniega     210
4  01006  Araba/Álava           Armiñón     467

In [4]:
DensidadPoblacion.rename({'ID_REL': 'Codigo Municipio'}, axis=1, inplace=True)

Cargamos la tabla 01_Output_ProvMun20.xlsx para posteriormente realizar el merge con DensidadPoblacion:

In [5]:
ProvMun = pd.read_excel('01_Output_ProvMun20.xlsx', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

In [6]:
AltitudMunicipios20 = DensidadPoblacion.merge(ProvMun, on='Codigo Municipio')
AltitudMunicipios20.head()

,Codigo Municipio,PROVINCIA,NOMBRE_ACTUAL,ALTITUD,Nombre Provincia,Codigo Provincia,Nombre Municipio
0,01001,Araba/Álava,Alegría-Dulantzi,568,Araba/Álava,01,Alegría-Dulantzi
1,01002,Araba/Álava,Amurrio,219,Araba/Álava,01,Amurrio
2,01003,Araba/Álava,Aramaio,333,Araba/Álava,01,Aramaio
3,01004,Araba/Álava,Artziniega,210,Araba/Álava,01,Artziniega
4,01006,Araba/Álava,Armiñón,467,Araba/Álava,01,Armiñón

In [7]:
AltitudMunicipios20.rename({'ALTITUD':'Altitud'}, axis=1, inplace=True)
AltitudMunicipios20['Y2020'] = 2020
ColNue = ['Y2020', 'Nombre Provincia', 'Codigo Provincia', 'Nombre Municipio', 'Codigo Municipio', 'Altitud']
AltitudMunicipios20 = AltitudMunicipios20[ColNue]
AltitudMunicipios20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Altitud
0,2020,Araba/Álava,01,Alegría-Dulantzi,01001,568
1,2020,Araba/Álava,01,Amurrio,01002,219
2,2020,Araba/Álava,01,Aramaio,01003,333
3,2020,Araba/Álava,01,Artziniega,01004,210
4,2020,Araba/Álava,01,Armiñón,01006,467

In [8]:
AltitudMunicipios20.to_excel('04_Output_Altitud_Municipios_20.xlsx', header = True, index = False)