## Nacimientos, matrimonios y defunciones 2020 y 2010

En este notebook procesaremos, para cada año, 52 JSON, uno por cada provincia y ciudad autónoma.  
Cada uno de ellos contiene el total de nacimientos, matrimonios y defunciones por municipios en 2020 y 2010.

In [104]:
import pandas as pd
import numpy as np
import requests

Para extraer tanto los datos de 2020 como de 2010, utilizaremos la siguiente función que tiene como argumento una lista con el número de tabla de cada una de las provincias y ciudades autónomas:

In [139]:
def ine_datos(CodPro):
    
    PobNacList = list()
    NacList = list()
    PobMatList = list()
    MatList = list()
    PobDefList = list()
    DefList = list()
    
    for codigo in CodPro:
        path = 'https://servicios.ine.es/wstempus/js/es/DATOS_TABLA/{cod_serie}?tip=AM&'
        path = path.format(cod_serie=codigo)
        json_request = requests.get(path).json()
        for dato in json_request: 
            for i in range(0,len(dato['Data'])):
                if 'nacidos vivos por residencia materna' in dato['Nombre']:
                    PobNacList.append(dato['Nombre'])
                    NacList.append(dato['Data'][i]['Valor'])
                elif 'matrimonios por el lugar en que han fijado residencia' in dato['Nombre']:
                    PobMatList.append(dato['Nombre'])
                    MatList.append(dato['Data'][i]['Valor'])
                elif 'fallecidos por el lugar de residencia' in dato['Nombre']:
                    PobDefList.append(dato['Nombre'])
                    DefList.append(dato['Data'][i]['Valor']) 
    
    Nacimientos = pd.DataFrame({
    'Codigo Municipio' : PobNacList,
    'Nacimientos': NacList
    })

    Matrimonios = pd.DataFrame({
    'Codigo Municipio' : PobMatList,
    'Matrimonios': MatList
    })

    Defunciones = pd.DataFrame({
    'Codigo Municipio' : PobMatList,
    'Defunciones': DefList
    }) 
    
    return

### Nacimientos, matrimonios y defunciones 2020
 
Obtendremos tres Dataframe con la siguiente información común:
- Y2020
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio 

Y con cada uno de ellos con uno de los siguientes campos:
- Nacimientos
- Matrimonios
- Defunciones

Codigos de las tablas correspondientes a 2020:

In [127]:
CodPro = list(range(50370, 50421+1))

In [128]:
ine_datos(CodPro)

In [129]:
Nacimientos = pd.DataFrame({
'Codigo Municipio' : PobNacList,
'Nacimientos': NacList
})

Matrimonios = pd.DataFrame({
'Codigo Municipio' : PobMatList,
'Matrimonios': MatList
})

Defunciones = pd.DataFrame({
'Codigo Municipio' : PobMatList,
'Defunciones': DefList
})

In [130]:
Nacimientos

                                       Codigo Municipio  Nacimientos
0     01051 Agurain/Salvatierra, nacidos vivos por r...         45.0
1     01001 Alegría-Dulantzi, nacidos vivos por resi...         17.0
2     01002 Amurrio, nacidos vivos por residencia ma...         85.0
3     01049 Añana, nacidos vivos por residencia materna          0.0
4     01003 Aramaio, nacidos vivos por residencia ma...          5.0
...                                                 ...          ...
8126  50296 Zaida, La, nacidos vivos por residencia ...          0.0
8127  50297 Zaragoza, nacidos vivos por residencia m...       4783.0
8128  50298 Zuera, nacidos vivos por residencia materna         67.0
8129  51001 Ceuta, nacidos vivos por residencia materna        843.0
8130  52001 Melilla, nacidos vivos por residencia ma...        962.0

[8131 rows x 2 columns]

Cargamos la tabla 01_Output_ProvMun20.xlsx para posteriormente realizar el merge con las tablas anteriores:

In [109]:
ProvMun = pd.read_excel('01_Output_ProvMun_20.xlsx', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

Incluimos en las tablas Nacimientos, Matrimonios y Defunciones el campo Codigo Municipio:

In [110]:
MunList = ProvMun['Codigo Municipio'].tolist()

In [111]:
def check_list(x):
    for l in MunList:
        if l in x:
            return l
    return ''

In [112]:
Nacimientos['Codigo Municipio'] = Nacimientos['Codigo Municipio'].map(lambda x: check_list(x))
Matrimonios['Codigo Municipio'] = Matrimonios['Codigo Municipio'].map(lambda x: check_list(x))
Defunciones['Codigo Municipio'] = Defunciones['Codigo Municipio'].map(lambda x: check_list(x))

Realizamos el merge con la tabla ProvMun:

In [113]:
Nacimientos20 = Nacimientos.merge(ProvMun, on='Codigo Municipio')
Matrimonios20 = Matrimonios.merge(ProvMun, on='Codigo Municipio')
Defunciones20 = Defunciones.merge(ProvMun, on='Codigo Municipio')

In [114]:
Nacimientos20['Y2020'] = 2020
ColNue = ['Y2020', 'Nombre Provincia', 'Codigo Provincia', 'Nombre Municipio','Codigo Municipio', 'Nacimientos']
Nacimientos20= Nacimientos20[ColNue]
Nacimientos20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Nacimientos
0,2020,Araba/Álava,01,Agurain/Salvatierra,01051,45.0
1,2020,Araba/Álava,01,Alegría-Dulantzi,01001,17.0
2,2020,Araba/Álava,01,Amurrio,01002,85.0
3,2020,Araba/Álava,01,Añana,01049,0.0
4,2020,Araba/Álava,01,Aramaio,01003,5.0

In [115]:
Matrimonios20['Y2020'] = 2020
ColNue = ['Y2020','Nombre Provincia', 'Codigo Provincia', 'Nombre Municipio','Codigo Municipio', 'Matrimonios']
Matrimonios20= Matrimonios20[ColNue]
Matrimonios20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Matrimonios
0,2020,Araba/Álava,01,Agurain/Salvatierra,01051,7.0
1,2020,Araba/Álava,01,Alegría-Dulantzi,01001,2.0
2,2020,Araba/Álava,01,Amurrio,01002,22.0
3,2020,Araba/Álava,01,Añana,01049,0.0
4,2020,Araba/Álava,01,Aramaio,01003,4.0

In [116]:
Defunciones20['Y2020'] = 2020
ColNue = ['Y2020','Nombre Provincia', 'Codigo Provincia', 'Nombre Municipio','Codigo Municipio', 'Defunciones']
Defunciones20= Defunciones20[ColNue]
Defunciones20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Defunciones
0,2020,Araba/Álava,01,Agurain/Salvatierra,01051,50.0
1,2020,Araba/Álava,01,Alegría-Dulantzi,01001,11.0
2,2020,Araba/Álava,01,Amurrio,01002,98.0
3,2020,Araba/Álava,01,Añana,01049,2.0
4,2020,Araba/Álava,01,Aramaio,01003,18.0

In [ ]:
Nacimientos20.to_excel('05_Output_Nacimientos_20.xlsx', header = True, index = False)
Matrimonios20.to_excel('05_Output_Matrimonios_20.xlsx', header = True, index = False)
Defunciones20.to_excel('05_Output_Defunciones_20.xlsx', header = True, index = False)

### Nacimientos, matrimonios y defunciones 2010
 
Obtendremos tres Dataframe con la siguiente información común:
- Y2010
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio 

Y con cada uno de ellos con uno de los siguientes campos:
- Nacimientos
- Matrimonios
- Defunciones

Codigos de las tablas correspondientes a 2010:

In [140]:
CodPro = list(range(22863, 22914+1))

In [141]:
ine_datos(CodPro)

In [142]:
Defunciones

                                       Codigo Municipio  Defunciones
0     01051 Agurain/Salvatierra, matrimonios por el ...         50.0
1     01001 Alegría-Dulantzi, matrimonios por el lug...         11.0
2     01002 Amurrio, matrimonios por el lugar en que...         98.0
3     01049 Añana, matrimonios por el lugar en que h...          2.0
4     01003 Aramaio, matrimonios por el lugar en que...         18.0
...                                                 ...          ...
8126  50296 Zaida, La, matrimonios por el lugar en q...          6.0
8127  50297 Zaragoza, matrimonios por el lugar en qu...       7999.0
8128  50298 Zuera, matrimonios por el lugar en que h...         80.0
8129  51001 Ceuta, matrimonios por el lugar en que h...        648.0
8130  52001 Melilla, matrimonios por el lugar en que...        602.0

[8131 rows x 2 columns]

Cargamos la tabla 01_Output_ProvMun10.xlsx para posteriormente realizar el merge con las tablas anteriores:

In [71]:
ProvMun = pd.read_excel('01_Output_ProvMun_10.xlsx', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

In [72]:
MunList = ProvMun['Codigo Municipio'].tolist()

In [73]:
def check_list(x):
    for l in MunList:
        if l in x:
            return l
    return ''

In [101]:
Nacimientos['Codigo Municipio'] = Nacimientos['Codigo Municipio'].map(lambda x: check_list(x))
Matrimonios['Codigo Municipio'] = Matrimonios['Codigo Municipio'].map(lambda x: check_list(x))
Defunciones['Codigo Municipio'] = Defunciones['Codigo Municipio'].map(lambda x: check_list(x))

Realizamos el merge con la tabla ProvMun:

In [102]:
Nacimientos10 = Nacimientos.merge(ProvMun, on='Codigo Municipio')
Matrimonios10 = Matrimonios.merge(ProvMun, on='Codigo Municipio')
Defunciones10 = Defunciones.merge(ProvMun, on='Codigo Municipio')

In [103]:
Nacimientos10['Y2010'] = 2010
ColNue = ['Y2010', 'Nombre Provincia', 'Codigo Provincia', 'Nombre Municipio','Codigo Municipio', 'Nacimientos']
Nacimientos10= Nacimientos10[ColNue]
Nacimientos10

,Y2010,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Nacimientos
0,2010,Araba/Álava,01,Agurain/Salvatierra,01051,45.0
1,2010,Araba/Álava,01,Alegría-Dulantzi,01001,17.0
2,2010,Araba/Álava,01,Amurrio,01002,85.0
3,2010,Araba/Álava,01,Añana,01049,0.0
4,2010,Araba/Álava,01,Aramaio,01003,5.0
...,...,...,...,...,...,...
8126,2010,Zaragoza,50,"Zaida, La",50296,0.0
8127,2010,Zaragoza,50,Zaragoza,50297,4783.0
8128,2010,Zaragoza,50,Zuera,50298,67.0
8129,2010,Ceuta,51,Ceuta,51001,843.0
8130,2010,Melilla,52,Melilla,52001,962.0

In [78]:
Matrimonios10['Y2010'] = 2010
ColNue = ['Y2010','Nombre Provincia', 'Codigo Provincia', 'Nombre Municipio','Codigo Municipio', 'Matrimonios']
Matrimonios10= Matrimonios10[ColNue]
Matrimonios10.head()

,Y2010,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Matrimonios
0,2010,Araba/Álava,01,Agurain/Salvatierra,01051,7.0
1,2010,Araba/Álava,01,Alegría-Dulantzi,01001,2.0
2,2010,Araba/Álava,01,Amurrio,01002,22.0
3,2010,Araba/Álava,01,Añana,01049,0.0
4,2010,Araba/Álava,01,Aramaio,01003,4.0

In [79]:
Defunciones10['Y2010'] = 2010
ColNue = ['Y2010','Nombre Provincia', 'Codigo Provincia', 'Nombre Municipio','Codigo Municipio', 'Defunciones']
Defunciones10= Defunciones10[ColNue]
Defunciones10.head()

,Y2010,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Defunciones
0,2010,Araba/Álava,01,Agurain/Salvatierra,01051,50.0
1,2010,Araba/Álava,01,Alegría-Dulantzi,01001,11.0
2,2010,Araba/Álava,01,Amurrio,01002,98.0
3,2010,Araba/Álava,01,Añana,01049,2.0
4,2010,Araba/Álava,01,Aramaio,01003,18.0

In [ ]:
Nacimientos10.to_excel('05_Output_Nacimientos_10.xlsx', header = True, index = False)
Matrimonios10.to_excel('05_Output_Matrimonios_10.xlsx', header = True, index = False)
Defunciones10.to_excel('05_Output_Defunciones_10.xlsx', header = True, index = False)