## Afiliados Seguridad Social 2020 y 2010
En este notebook procesaremos dos Excel, uno para cada uno de los años.  
Estos archivos contienen el número de afiliados dentro del régimen general, agrario, hogar, mar, autónomos, carbón y una última columna con el total.

In [1]:
import pandas as pd
import numpy as np

### Afiliados Seguridad Social 2020
Obtendremos un DataFrame con la siguiente información:
- Y2020
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio
- Regimen General
- Regimen Agrario
- Regimen Hogar
- Regimen MaR
- Regimen Autonomos
- Regimen Carbon
- Total Regimen SS

In [2]:
AfiliadosSS20 = pd.read_excel('07_Input_Afiliados_SS_20.xlsx',dtype='object')
AfiliadosSS20.head()

,PROVINCIA,CODIGO,MUNICIPIO,TRAB,Reg. General,R. G.- S.E.Agrario,R. G.- S.E.Hogar,R. E. MAR,R. E. T. Autónomos,R. E. M. Carbón,TOTAL
0,01 ARABA/ÁLAVA,01001,ALEGRIA-DULANTZI,TRAB.,496,<5,17,0,198,0,>=712
1,01 ARABA/ÁLAVA,01002,AMURRIO,TRAB.,3170,9,94,0,622,0,3895
2,01 ARABA/ÁLAVA,01003,ARAMAIO,TRAB.,175,<5,5,0,61,0,>=242
3,01 ARABA/ÁLAVA,01004,ARTZINIEGA,TRAB.,279,<5,14,0,111,0,>=405
4,01 ARABA/ÁLAVA,01006,ARMIÑON,TRAB.,138,0,0,0,20,0,158

Cargamos la tabla 01_Output_ProvMun_20.xlsx para posteriormente realizar el merge con AfiliadosSS20:

In [3]:
ProvMun = pd.read_excel('01_Output_ProvMun_20.xlsx', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

In [4]:
AfiliadosSS20.rename({'CODIGO':'Codigo Municipio'}, axis=1, inplace=True)

In [5]:
AfiliadosSS20 = AfiliadosSS20.merge(ProvMun, on='Codigo Municipio')
AfiliadosSS20.head()

,PROVINCIA,Codigo Municipio,MUNICIPIO,TRAB,Reg. General,R. G.- S.E.Agrario,R. G.- S.E.Hogar,R. E. MAR,R. E. T. Autónomos,R. E. M. Carbón,TOTAL,Nombre Provincia,Codigo Provincia,Nombre Municipio
0,01 ARABA/ÁLAVA,01001,ALEGRIA-DULANTZI,TRAB.,496,<5,17,0,198,0,>=712,Araba/Álava,01,Alegría-Dulantzi
1,01 ARABA/ÁLAVA,01002,AMURRIO,TRAB.,3170,9,94,0,622,0,3895,Araba/Álava,01,Amurrio
2,01 ARABA/ÁLAVA,01003,ARAMAIO,TRAB.,175,<5,5,0,61,0,>=242,Araba/Álava,01,Aramaio
3,01 ARABA/ÁLAVA,01004,ARTZINIEGA,TRAB.,279,<5,14,0,111,0,>=405,Araba/Álava,01,Artziniega
4,01 ARABA/ÁLAVA,01006,ARMIÑON,TRAB.,138,0,0,0,20,0,158,Araba/Álava,01,Armiñón

In [6]:
AfiliadosSS20['Y2020'] = 2020
AfiliadosSS20 = AfiliadosSS20.rename({'Reg. General': 'Regimen General',
                                     'R. G.- S.E.Agrario': 'Regimen Agrario', 
                                     'R. G.- S.E.Hogar' : 'Regimen Hogar', 
                                     'R. E. MAR ' : 'Regimen Mar', 
                                     'R. E. T. Autónomos' : 'Regimen Autonomos', 
                                     'R. E. M. Carbón' : 'Regimen Carbon'}, axis = 1)
ColNue = ['Y2020','Nombre Provincia', 'Codigo Provincia', 'Nombre Municipio', 'Codigo Municipio', 'Regimen General', 
          'Regimen Agrario', 'Regimen Hogar','Regimen Mar', 'Regimen Autonomos', 'Regimen Carbon']
AfiliadosSS20 = AfiliadosSS20[ColNue]
AfiliadosSS20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Regimen General,Regimen Agrario,Regimen Hogar,Regimen Mar,Regimen Autonomos,Regimen Carbon
0,2020,Araba/Álava,01,Alegría-Dulantzi,01001,496,<5,17,0,198,0
1,2020,Araba/Álava,01,Amurrio,01002,3170,9,94,0,622,0
2,2020,Araba/Álava,01,Aramaio,01003,175,<5,5,0,61,0
3,2020,Araba/Álava,01,Artziniega,01004,279,<5,14,0,111,0
4,2020,Araba/Álava,01,Armiñón,01006,138,0,0,0,20,0

Los valores que están entre 0 y 5 se indican en la tabla con <5. Substituimos estos valores por un 2.  
Ademá creamos una nueva columna con la suma de todas las columnas segun régimen.

In [7]:
AfiliadosSS20.dtypes

Y2020                 int64
Nombre Provincia     object
Codigo Provincia     object
Nombre Municipio     object
Codigo Municipio     object
Regimen General      object
Regimen Agrario      object
Regimen Hogar        object
Regimen Mar          object
Regimen Autonomos    object
Regimen Carbon       object
dtype: object

In [8]:
AfiliadosSS20 = AfiliadosSS20.applymap(lambda x: 2 if x == '<5' else x)

In [9]:
AfiliadosSS20[['Regimen General', 'Regimen Agrario','Regimen Hogar', 'Regimen Mar','Regimen Autonomos', 'Regimen Carbon']] = AfiliadosSS20[['Regimen General', 'Regimen Agrario','Regimen Hogar', 'Regimen Mar','Regimen Autonomos', 'Regimen Carbon']].astype(int)

In [10]:
AfiliadosSS20['Total Regimen SS'] = AfiliadosSS20['Regimen General'] + AfiliadosSS20['Regimen Agrario'] + AfiliadosSS20['Regimen Hogar'] + AfiliadosSS20['Regimen Mar'] + AfiliadosSS20['Regimen Autonomos'] + AfiliadosSS20['Regimen Carbon']

In [11]:
AfiliadosSS20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Regimen General,Regimen Agrario,Regimen Hogar,Regimen Mar,Regimen Autonomos,Regimen Carbon,Total Regimen SS
0,2020,Araba/Álava,01,Alegría-Dulantzi,01001,496,2,17,0,198,0,713
1,2020,Araba/Álava,01,Amurrio,01002,3170,9,94,0,622,0,3895
2,2020,Araba/Álava,01,Aramaio,01003,175,2,5,0,61,0,243
3,2020,Araba/Álava,01,Artziniega,01004,279,2,14,0,111,0,406
4,2020,Araba/Álava,01,Armiñón,01006,138,0,0,0,20,0,158

In [12]:
AfiliadosSS20.to_excel('07_Output_Afiliados_SS_20.xlsx', header = True, index = False)

### Afiliados Seguridad Social 2010
Obtendremos un DataFrame con la siguiente información:
- Y2010
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio
- Regimen General
- Regimen Agrario
- Regimen Hogar
- Regimen Mar
- Regimen Autonomos
- Regimen Carbon
- Total Regimen SS

In [13]:
AfiliadosSS10 = pd.read_excel('07_Input_Afiliados_SS_10.xlsx',dtype='object')
AfiliadosSS10.head()

,PROVINCIA,CODIGO,MUNICIPIO,TRAB,GENERAL,AGRARIO,MAR,HOGAR,AUTONOMOS,CARBON,TOTAL
0,01 ALAVA,01001,ALEGRIA-DULANTZI,TRAB.,637,<5,0,8,186,0,832
1,01 ALAVA,01002,AMURRIO,TRAB.,3836,14,0,46,622,0,4518
2,01 ALAVA,01003,ARAMAIO,TRAB.,116,<5,0,<5,73,0,196
3,01 ALAVA,01004,ARTZINIEGA,TRAB.,297,6,0,<5,105,0,412
4,01 ALAVA,01006,ARMIÑON,TRAB.,121,0,0,0,21,0,142

Cargamos la tabla 01_Output_ProvMun_10.xlsx para posteriormente realizar el merge con AfiliadosSS10:

In [14]:
ProvMun = pd.read_excel('01_Output_ProvMun_10.xlsx', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

In [15]:
AfiliadosSS10.rename({'CODIGO':'Codigo Municipio'}, axis=1, inplace=True)

In [16]:
AfiliadosSS10 = AfiliadosSS10.merge(ProvMun, on='Codigo Municipio')
AfiliadosSS10.head()

,PROVINCIA,Codigo Municipio,MUNICIPIO,TRAB,GENERAL,AGRARIO,MAR,HOGAR,AUTONOMOS,CARBON,TOTAL,Nombre Provincia,Codigo Provincia,Nombre Municipio
0,01 ALAVA,01001,ALEGRIA-DULANTZI,TRAB.,637,<5,0,8,186,0,832,Araba/Álava,01,Alegría-Dulantzi
1,01 ALAVA,01002,AMURRIO,TRAB.,3836,14,0,46,622,0,4518,Araba/Álava,01,Amurrio
2,01 ALAVA,01003,ARAMAIO,TRAB.,116,<5,0,<5,73,0,196,Araba/Álava,01,Aramaio
3,01 ALAVA,01004,ARTZINIEGA,TRAB.,297,6,0,<5,105,0,412,Araba/Álava,01,Artziniega
4,01 ALAVA,01006,ARMIÑON,TRAB.,121,0,0,0,21,0,142,Araba/Álava,01,Armiñón

In [17]:
AfiliadosSS10['Y2010'] = 2010
AfiliadosSS10 = AfiliadosSS10.rename({'GENERAL': 'Regimen General',
                                     'AGRARIO': 'Regimen Agrario', 
                                     'HOGAR' : 'Regimen Hogar', 
                                     'MAR' : 'Regimen Mar', 
                                     'AUTONOMOS' : 'Regimen Autonomos', 
                                     'CARBON' : 'Regimen Carbon'}, axis = 1)
ColNue = ['Y2010','Nombre Provincia', 'Codigo Provincia', 'Nombre Municipio', 'Codigo Municipio', 'Regimen General', 
          'Regimen Agrario', 'Regimen Hogar','Regimen Mar', 'Regimen Autonomos', 'Regimen Carbon']
AfiliadosSS10 = AfiliadosSS10[ColNue]
AfiliadosSS10.head()

,Y2010,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Regimen General,Regimen Agrario,Regimen Hogar,Regimen Mar,Regimen Autonomos,Regimen Carbon
0,2010,Araba/Álava,01,Alegría-Dulantzi,01001,637,<5,8,0,186,0
1,2010,Araba/Álava,01,Amurrio,01002,3836,14,46,0,622,0
2,2010,Araba/Álava,01,Aramaio,01003,116,<5,<5,0,73,0
3,2010,Araba/Álava,01,Artziniega,01004,297,6,<5,0,105,0
4,2010,Araba/Álava,01,Armiñón,01006,121,0,0,0,21,0

Los valores que están entre 0 y 5 se indican en la tabla con <5. Substituimos estos valores por un 2.  
Ademá creamos una nueva columna con la suma de todas las columnas segun régimen.

In [18]:
AfiliadosSS10.dtypes

Y2010                 int64
Nombre Provincia     object
Codigo Provincia     object
Nombre Municipio     object
Codigo Municipio     object
Regimen General      object
Regimen Agrario      object
Regimen Hogar        object
Regimen Mar          object
Regimen Autonomos    object
Regimen Carbon       object
dtype: object

In [19]:
AfiliadosSS10 = AfiliadosSS10.applymap(lambda x: 2 if x == '<5' else x)

In [20]:
AfiliadosSS10[['Regimen General', 'Regimen Agrario','Regimen Hogar', 'Regimen Mar','Regimen Autonomos', 'Regimen Carbon']] = AfiliadosSS10[['Regimen General', 'Regimen Agrario','Regimen Hogar', 'Regimen Mar','Regimen Autonomos', 'Regimen Carbon']].astype(int)

In [21]:
AfiliadosSS10['Total Regimen SS'] = AfiliadosSS10['Regimen General'] + AfiliadosSS10['Regimen Agrario'] + AfiliadosSS10['Regimen Hogar'] + AfiliadosSS10['Regimen Mar'] + AfiliadosSS10['Regimen Autonomos'] + AfiliadosSS10['Regimen Carbon']

In [22]:
AfiliadosSS10.head()

,Y2010,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Regimen General,Regimen Agrario,Regimen Hogar,Regimen Mar,Regimen Autonomos,Regimen Carbon,Total Regimen SS
0,2010,Araba/Álava,01,Alegría-Dulantzi,01001,637,2,8,0,186,0,833
1,2010,Araba/Álava,01,Amurrio,01002,3836,14,46,0,622,0,4518
2,2010,Araba/Álava,01,Aramaio,01003,116,2,2,0,73,0,193
3,2010,Araba/Álava,01,Artziniega,01004,297,6,2,0,105,0,410
4,2010,Araba/Álava,01,Armiñón,01006,121,0,0,0,21,0,142

In [23]:
AfiliadosSS10.to_excel('07_Output_Afiliados_SS_10.xlsx', header = True, index = False)