## Contratos laborales 2020 y 2010

En este notebook procesaremos dos Excel, uno para cada uno de los años.  
Estos archivos contienen el número de contratos laborales por municipios, por tipo de contrato; temporal e indefinido, por sexo, y por sector; agricultura, industria, construcción y servicios.

In [1]:
import pandas as pd
import numpy as np

### Contratos laborales 2020
Obtendremos un DataFrame con la siguiente información:
- Y2020
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio
- Total Contratos
- Contratos iniciales indefinidos hombres
- Contratos iniciales temporales hombres
- Contratos convertidos en indefinidos hombres
- Contratos iniciales indefinidos mujeres
- Contratos iniciales temporales mujeres
- Contratos convertidos en indefinidos mujeres
- Contratos  Agricultura
- Contratos  Industria
- Contratos Construcción
- Contratos  Servicios

In [2]:
ContratosLaborales20 = pd.read_excel('08_Input_Contratos_Laborales_20.xls',dtype='object')
ContratosLaborales20.head()

,Año,Código de CA,Comunidad Autónoma,Codigo Provincia,Provincia,Codigo Municipio,Municipio,Total Contratos,Contratos iniciales indefinidos hombres,Contratos iniciales temporales hombres,Contratos convertidos en indefinidos hombres,Contratos iniciales indefinidos mujeres,Contratos iniciales temporales mujeres,Contratos convertidos en indefinidos mujeres,Contratos Agricultura,Contratos Industria,Contratos Construcción,Contratos Servicios
0,2020,16,País Vasco,1,Araba/Álava,01001,Alegría-Dulantzi,34,2,11,4,0,15,2,0,4,0,30
1,2020,16,País Vasco,1,Araba/Álava,01002,Amurrio,279,5,162,4,2,103,3,2,193,15,69
2,2020,16,País Vasco,1,Araba/Álava,01003,Aramaio,14,1,5,0,2,6,0,0,4,1,9
3,2020,16,País Vasco,1,Araba/Álava,01004,Artziniega,30,0,25,2,0,3,0,0,19,4,7
4,2020,16,País Vasco,1,Araba/Álava,01006,Armiñón,5,0,4,0,0,1,0,0,5,0,0

In [3]:
ContratosLaborales20.drop(['Código de CA', 'Comunidad Autónoma', 'Codigo Provincia', 'Provincia', ' Municipio'], axis=1, inplace=True)

Cargamos la tabla 01_Output_ProvMun_20.xlsx para posteriormente realizar el merge con ContratosLaborales20:

In [4]:
ProvMun = pd.read_excel('01_Output_ProvMun_20.xlsx', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

In [5]:
ContratosLaborales20 = ContratosLaborales20.merge(ProvMun, on='Codigo Municipio')
ContratosLaborales20.head()

,Año,Codigo Municipio,Total Contratos,Contratos iniciales indefinidos hombres,Contratos iniciales temporales hombres,Contratos convertidos en indefinidos hombres,Contratos iniciales indefinidos mujeres,Contratos iniciales temporales mujeres,Contratos convertidos en indefinidos mujeres,Contratos Agricultura,Contratos Industria,Contratos Construcción,Contratos Servicios,Nombre Provincia,Codigo Provincia,Nombre Municipio
0,2020,01001,34,2,11,4,0,15,2,0,4,0,30,Araba/Álava,01,Alegría-Dulantzi
1,2020,01002,279,5,162,4,2,103,3,2,193,15,69,Araba/Álava,01,Amurrio
2,2020,01003,14,1,5,0,2,6,0,0,4,1,9,Araba/Álava,01,Aramaio
3,2020,01004,30,0,25,2,0,3,0,0,19,4,7,Araba/Álava,01,Artziniega
4,2020,01006,5,0,4,0,0,1,0,0,5,0,0,Araba/Álava,01,Armiñón

In [6]:
ContratosLaborales20 = ContratosLaborales20.rename({'Año': 'Y2020'}, axis = 1)
ColNue = ['Y2020','Nombre Provincia', 'Codigo Provincia', 'Nombre Municipio', 'Codigo Municipio', 'Total Contratos',
          'Contratos iniciales indefinidos hombres', 
          'Contratos iniciales temporales hombres','Contratos convertidos en indefinidos hombres', 
          'Contratos iniciales indefinidos mujeres', 'Contratos iniciales temporales mujeres',
          'Contratos convertidos en indefinidos mujeres', 'Contratos  Agricultura','Contratos  Industria', 
          'Contratos Construcción', 'Contratos  Servicios']
ContratosLaborales20 = ContratosLaborales20[ColNue]
ContratosLaborales20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Total Contratos,Contratos iniciales indefinidos hombres,Contratos iniciales temporales hombres,Contratos convertidos en indefinidos hombres,Contratos iniciales indefinidos mujeres,Contratos iniciales temporales mujeres,Contratos convertidos en indefinidos mujeres,Contratos Agricultura,Contratos Industria,Contratos Construcción,Contratos Servicios
0,2020,Araba/Álava,01,Alegría-Dulantzi,01001,34,2,11,4,0,15,2,0,4,0,30
1,2020,Araba/Álava,01,Amurrio,01002,279,5,162,4,2,103,3,2,193,15,69
2,2020,Araba/Álava,01,Aramaio,01003,14,1,5,0,2,6,0,0,4,1,9
3,2020,Araba/Álava,01,Artziniega,01004,30,0,25,2,0,3,0,0,19,4,7
4,2020,Araba/Álava,01,Armiñón,01006,5,0,4,0,0,1,0,0,5,0,0

In [7]:
ContratosLaborales20.to_excel('08_Output_Contratos_Laborales_20.xlsx', header = True, index = False)

### Contratos laborales 2010
Obtendremos un DataFrame con la siguiente información:
- Y2010
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio
- Total Contratos
- Contratos iniciales indefinidos hombres
- Contratos iniciales temporales hombres
- Contratos convertidos en indefinidos hombres
- Contratos iniciales indefinidos mujeres
- Contratos iniciales temporales mujeres
- Contratos convertidos en indefinidos mujeres
- Contratos  Agricultura
- Contratos  Industria
- Contratos Construcción
- Contratos  Servicios

In [8]:
ContratosLaborales10 = pd.read_excel('08_Input_Contratos_Laborales_10.xls',dtype='object')
ContratosLaborales10.head()

,Año,Código de CA,Comunidad Autónoma,Codigo Provincia,Provincia,Codigo Municipio,Municipio,Total Contratos,Contratos iniciales indefinidos hombres,Contratos iniciales temporales hombres,Contratos convertidos en indefinidos hombres,Contratos iniciales indefinidos mujeres,Contratos iniciales temporales mujeres,Contratos convertidos en indefinidos mujeres,Contratos Agricultura,Contratos Industria,Contratos Construcción,Contratos Servicios
0,2010,16,País Vasco,1,Araba/Álava,01001,Alegría-Dulantzi,31,0,24,0,0,7,0,0,3,13,15
1,2010,16,País Vasco,1,Araba/Álava,01002,Amurrio,382,3,276,15,1,82,5,2,227,14,139
2,2010,16,País Vasco,1,Araba/Álava,01003,Aramaio,6,0,4,0,0,2,0,0,0,0,6
3,2010,16,País Vasco,1,Araba/Álava,01004,Artziniega,9,0,2,1,0,4,2,0,1,1,7
4,2010,16,País Vasco,1,Araba/Álava,01006,Armiñón,3,0,0,0,0,1,2,0,3,0,0

In [9]:
ContratosLaborales10.drop(['Código de CA', 'Comunidad Autónoma', 'Codigo Provincia', 'Provincia', ' Municipio'], axis=1, inplace=True)

Cargamos la tabla 01_Output_ProvMun_10.xlsx para posteriormente realizar el merge con ContratosLaborales10:

In [10]:
ProvMun = pd.read_excel('01_Output_ProvMun_10.xlsx', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

In [11]:
ContratosLaborales10 = ContratosLaborales10.merge(ProvMun, on='Codigo Municipio')
ContratosLaborales10.head()

,Año,Codigo Municipio,Total Contratos,Contratos iniciales indefinidos hombres,Contratos iniciales temporales hombres,Contratos convertidos en indefinidos hombres,Contratos iniciales indefinidos mujeres,Contratos iniciales temporales mujeres,Contratos convertidos en indefinidos mujeres,Contratos Agricultura,Contratos Industria,Contratos Construcción,Contratos Servicios,Nombre Provincia,Codigo Provincia,Nombre Municipio
0,2010,01001,31,0,24,0,0,7,0,0,3,13,15,Araba/Álava,01,Alegría-Dulantzi
1,2010,01002,382,3,276,15,1,82,5,2,227,14,139,Araba/Álava,01,Amurrio
2,2010,01003,6,0,4,0,0,2,0,0,0,0,6,Araba/Álava,01,Aramaio
3,2010,01004,9,0,2,1,0,4,2,0,1,1,7,Araba/Álava,01,Artziniega
4,2010,01006,3,0,0,0,0,1,2,0,3,0,0,Araba/Álava,01,Armiñón

In [12]:
ContratosLaborales10 = ContratosLaborales10.rename({'Año': 'Y2010'}, axis = 1)
ColNue = ['Y2010','Nombre Provincia', 'Codigo Provincia', 'Nombre Municipio', 'Codigo Municipio', 'Total Contratos',
          'Contratos iniciales indefinidos hombres', 
          'Contratos iniciales temporales hombres','Contratos convertidos en indefinidos hombres', 
          'Contratos iniciales indefinidos mujeres', 'Contratos iniciales temporales mujeres',
          'Contratos convertidos en indefinidos mujeres', 'Contratos  Agricultura','Contratos  Industria', 
          'Contratos Construcción', 'Contratos  Servicios']
ContratosLaborales10 = ContratosLaborales10[ColNue]
ContratosLaborales10.head()

,Y2010,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Total Contratos,Contratos iniciales indefinidos hombres,Contratos iniciales temporales hombres,Contratos convertidos en indefinidos hombres,Contratos iniciales indefinidos mujeres,Contratos iniciales temporales mujeres,Contratos convertidos en indefinidos mujeres,Contratos Agricultura,Contratos Industria,Contratos Construcción,Contratos Servicios
0,2010,Araba/Álava,01,Alegría-Dulantzi,01001,31,0,24,0,0,7,0,0,3,13,15
1,2010,Araba/Álava,01,Amurrio,01002,382,3,276,15,1,82,5,2,227,14,139
2,2010,Araba/Álava,01,Aramaio,01003,6,0,4,0,0,2,0,0,0,0,6
3,2010,Araba/Álava,01,Artziniega,01004,9,0,2,1,0,4,2,0,1,1,7
4,2010,Araba/Álava,01,Armiñón,01006,3,0,0,0,0,1,2,0,3,0,0

In [13]:
ContratosLaborales10.to_excel('08_Output_Contratos_Laborales_10.xlsx', header = True, index = False)