### Parados 2020 y 2010
En este notebook procesaremos dos Excel, uno para cada uno de los años.  
Estos archivos contienen el paro registrado, por municipios, sexo, edad; <25, 25-45, >45, y sector de actividad económica; agricultura, industria, construcción, servicios y parados de larga duración.

In [1]:
import pandas as pd

### Parados 2020
Obtendremos un DataFrame con la siguiente información:
- Y2020
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio
- Paro hombre edad < 25
- Paro hombre edad 25-45
- Paro hombre edad >=45
- Paro mujer edad < 25
- Paro mujer edad 25-45
- Paro mujer edad >=45
- Paro Agricultura
- Paro Industria
- Paro Construcción
- Paro Servicios
- Paro Sin empleo Anterior

In [2]:
Parados20 = pd.read_excel('09_Input_Parados_20.xls',dtype='object')
Parados20.head()

,Año,Código de CA,Comunidad Autónoma,Codigo Provincia,Provincia,Codigo Municipio,Municipio,total Paro Registrado,Paro hombre edad < 25,Paro hombre edad 25 -45,Paro hombre edad >=45,Paro mujer edad < 25,Paro mujer edad 25 -45,Paro mujer edad >=45,Paro Agricultura,Paro Industria,Paro Construcción,Paro Servicios,Paro Sin empleo Anterior
0,2020,16,País Vasco,1,Araba/Álava,01001,Alegría-Dulantzi,192,19,36,46,8,50,33,8,38,7,108,31
1,2020,16,País Vasco,1,Araba/Álava,01002,Amurrio,800,36,155,172,27,205,205,31,127,58,469,115
2,2020,16,País Vasco,1,Araba/Álava,01003,Aramaio,17,0,0,9,2,2,4,1,5,0,11,0
3,2020,16,País Vasco,1,Araba/Álava,01004,Artziniega,97,7,17,19,2,25,27,2,12,6,61,16
4,2020,16,País Vasco,1,Araba/Álava,01006,Armiñón,12,0,0,7,0,1,4,0,3,0,8,1

In [3]:
Parados20.drop(['Código de CA', 'Comunidad Autónoma', 'Codigo Provincia', 'Provincia', ' Municipio'], axis=1, inplace=True)

Cargamos la tabla 01_Output_ProvMun_20.xlsx para posteriormente realizar el merge con Parados20:

In [4]:
ProvMun = pd.read_excel('01_Output_ProvMun_20.xlsx', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

In [5]:
Parados20 = Parados20.merge(ProvMun, on='Codigo Municipio')
Parados20.head()

,Año,Codigo Municipio,total Paro Registrado,Paro hombre edad < 25,Paro hombre edad 25 -45,Paro hombre edad >=45,Paro mujer edad < 25,Paro mujer edad 25 -45,Paro mujer edad >=45,Paro Agricultura,Paro Industria,Paro Construcción,Paro Servicios,Paro Sin empleo Anterior,Nombre Provincia,Codigo Provincia,Nombre Municipio
0,2020,01001,192,19,36,46,8,50,33,8,38,7,108,31,Araba/Álava,01,Alegría-Dulantzi
1,2020,01002,800,36,155,172,27,205,205,31,127,58,469,115,Araba/Álava,01,Amurrio
2,2020,01003,17,0,0,9,2,2,4,1,5,0,11,0,Araba/Álava,01,Aramaio
3,2020,01004,97,7,17,19,2,25,27,2,12,6,61,16,Araba/Álava,01,Artziniega
4,2020,01006,12,0,0,7,0,1,4,0,3,0,8,1,Araba/Álava,01,Armiñón

In [6]:
Parados20 = Parados20.rename({'Año': 'Y2020'}, axis = 1)
ColNue = ['Y2020','Nombre Provincia', 'Codigo Provincia', 'Nombre Municipio','total Paro Registrado', 
          'Paro hombre edad < 25', 'Paro hombre edad 25 -45 ','Paro hombre edad >=45', 'Paro mujer edad < 25', 
          'Paro mujer edad 25 -45 ', 'Paro mujer edad >=45', 'Paro Agricultura','Paro Industria', 'Paro Construcción', 'Paro Servicios', 
          'Paro Sin empleo Anterior']
Parados20 = Parados20[ColNue]
Parados20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,total Paro Registrado,Paro hombre edad < 25,Paro hombre edad 25 -45,Paro hombre edad >=45,Paro mujer edad < 25,Paro mujer edad 25 -45,Paro mujer edad >=45,Paro Agricultura,Paro Industria,Paro Construcción,Paro Servicios,Paro Sin empleo Anterior
0,2020,Araba/Álava,01,Alegría-Dulantzi,192,19,36,46,8,50,33,8,38,7,108,31
1,2020,Araba/Álava,01,Amurrio,800,36,155,172,27,205,205,31,127,58,469,115
2,2020,Araba/Álava,01,Aramaio,17,0,0,9,2,2,4,1,5,0,11,0
3,2020,Araba/Álava,01,Artziniega,97,7,17,19,2,25,27,2,12,6,61,16
4,2020,Araba/Álava,01,Armiñón,12,0,0,7,0,1,4,0,3,0,8,1

In [7]:
Parados20.to_excel('09_Output_Parados_20.xlsx', header = True, index = False)

### Parados 2010
Obtendremos un DataFrame con la siguiente información:
- Y2010
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio
- Paro hombre edad < 25
- Paro hombre edad 25-45
- Paro hombre edad >=45
- Paro mujer edad < 25
- Paro mujer edad 25-45
- Paro mujer edad >=45
- Paro Agricultura
- Paro Industria
- Paro Construcción
- Paro Servicios
- Paro Sin empleo Anterior

In [8]:
Parados10 = pd.read_excel('09_Input_Parados_10.xls',dtype='object')
Parados10.head()

,Año,Código de CA,Comunidad Autónoma,Codigo Provincia,Provincia,Codigo Municipio,Municipio,total Paro Registrado,Paro hombre edad < 25,Paro hombre edad 25 -45,Paro hombre edad >=45,Paro mujer edad < 25,Paro mujer edad 25 -45,Paro mujer edad >=45,Paro Agricultura,Paro Industria,Paro Construcción,Paro Servicios,Paro Sin empleo Anterior
0,2010,16,País Vasco,1,Araba/Álava,01001,Alegría-Dulantzi,147,7,44,20,10,50,16,3,30,13,97,4
1,2010,16,País Vasco,1,Araba/Álava,01002,Amurrio,601,31,135,105,31,158,141,9,114,73,384,21
2,2010,16,País Vasco,1,Araba/Álava,01003,Aramaio,30,2,5,11,2,5,5,0,17,0,13,0
3,2010,16,País Vasco,1,Araba/Álava,01004,Artziniega,132,6,34,16,3,48,25,2,23,10,90,7
4,2010,16,País Vasco,1,Araba/Álava,01006,Armiñón,14,1,3,1,0,6,3,0,3,2,9,0

In [9]:
Parados10.drop(['Código de CA', 'Comunidad Autónoma', 'Codigo Provincia', 'Provincia', ' Municipio'], axis=1, inplace=True)

Cargamos la tabla 01_Output_ProvMun_10.xlsx para posteriormente realizar el merge con Parados10:

In [10]:
ProvMun = pd.read_excel('01_Output_ProvMun_10.xlsx', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

In [11]:
Parados10 = Parados10.merge(ProvMun, on='Codigo Municipio')
Parados10.head()

,Año,Codigo Municipio,total Paro Registrado,Paro hombre edad < 25,Paro hombre edad 25 -45,Paro hombre edad >=45,Paro mujer edad < 25,Paro mujer edad 25 -45,Paro mujer edad >=45,Paro Agricultura,Paro Industria,Paro Construcción,Paro Servicios,Paro Sin empleo Anterior,Nombre Provincia,Codigo Provincia,Nombre Municipio
0,2010,01001,147,7,44,20,10,50,16,3,30,13,97,4,Araba/Álava,01,Alegría-Dulantzi
1,2010,01002,601,31,135,105,31,158,141,9,114,73,384,21,Araba/Álava,01,Amurrio
2,2010,01003,30,2,5,11,2,5,5,0,17,0,13,0,Araba/Álava,01,Aramaio
3,2010,01004,132,6,34,16,3,48,25,2,23,10,90,7,Araba/Álava,01,Artziniega
4,2010,01006,14,1,3,1,0,6,3,0,3,2,9,0,Araba/Álava,01,Armiñón

In [12]:
Parados10 = Parados10.rename({'Año': 'Y2010'}, axis = 1)
ColNue = ['Y2010','Nombre Provincia', 'Codigo Provincia', 'Nombre Municipio','total Paro Registrado', 
          'Paro hombre edad < 25', 'Paro hombre edad 25 -45 ','Paro hombre edad >=45', 'Paro mujer edad < 25', 
          'Paro mujer edad 25 -45 ', 'Paro mujer edad >=45', 'Paro Agricultura','Paro Industria', 'Paro Construcción', 'Paro Servicios', 
          'Paro Sin empleo Anterior']
Parados10 = Parados10[ColNue]
Parados10.head()

,Y2010,Nombre Provincia,Codigo Provincia,Nombre Municipio,total Paro Registrado,Paro hombre edad < 25,Paro hombre edad 25 -45,Paro hombre edad >=45,Paro mujer edad < 25,Paro mujer edad 25 -45,Paro mujer edad >=45,Paro Agricultura,Paro Industria,Paro Construcción,Paro Servicios,Paro Sin empleo Anterior
0,2010,Araba/Álava,01,Alegría-Dulantzi,147,7,44,20,10,50,16,3,30,13,97,4
1,2010,Araba/Álava,01,Amurrio,601,31,135,105,31,158,141,9,114,73,384,21
2,2010,Araba/Álava,01,Aramaio,30,2,5,11,2,5,5,0,17,0,13,0
3,2010,Araba/Álava,01,Artziniega,132,6,34,16,3,48,25,2,23,10,90,7
4,2010,Araba/Álava,01,Armiñón,14,1,3,1,0,6,3,0,3,2,9,0

In [13]:
Parados10.to_excel('09_Output_Parados_10.xlsx', header = True, index = False)