## Explotaciones y hectáreas agrícolas 2020 y 2010
En este notebook procesaremos dos JSON, uno por cada uno de los años, con el número de explotaciones y hectáreas agrícolas desagregado por municipios.

In [1]:
import pandas as pd
import requests

### Explotaciones y hectáreas agrícolas 2020
Obtendremos un Dataframe con la siguiente información:
- Y2020
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio
- Nº Explotaciones Agricolas
- Nº Hectareas Agricolas

In [2]:
path = 'https://servicios.ine.es/wstempus/js/es/DATOS_TABLA/52071?tip=AM&'
json_request = requests.get(path).json()

In [3]:
CodExpList = list()
NumExpList = list()
CodSuperList = list()
NumSuperList = list()

In [4]:
for dato in json_request: 
    for i in range(0,len(dato['Data'])):
        if 'SAU, Nº explotaciones' in dato['Nombre']:
            CodExpList.append(dato['MetaData'][0]['Codigo'])
            NumExpList.append(dato['Data'][i]['Valor'])
        elif 'SAU, Superficie (ha.)' in dato['Nombre']:
            CodSuperList.append(dato['MetaData'][0]['Codigo'])
            NumSuperList.append(dato['Data'][i]['Valor'])

In [5]:
ExplotacionesGanaderas20 = pd.DataFrame({
        'Codigo Municipio' : CodExpList,
        'Nº Explotaciones Ganaderas': NumExpList
    })
HectareasGanaderas20 = pd.DataFrame({
        'Codigo Municipio' : CodSuperList,
        'Nº Hectareas Ganaderas': NumSuperList
    })

In [6]:
ExplotacionesGanaderas20.head()

  Codigo Municipio  Nº Explotaciones Ganaderas
0               00                    906916.0
1               01                    266819.0
2               04                     26438.0
3             0401                      1660.0
4            04037                       357.0

In [7]:
HectareasGanaderas20.head()

  Codigo Municipio  Nº Hectareas Ganaderas
0               00             23913682.29
1               01              4748844.31
2               04               203381.00
3             0401                58565.20
4            04037                13030.77

Cargamos la tabla 01_Output_ProvMun20.xlsx para posteriormente realizar el merge con ambos DataFrame:

In [8]:
ProvMun = pd.read_excel('01_Output_ProvMun_20.xlsx', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

In [9]:
ExplotacionesGanaderas20 = ProvMun.merge(ExplotacionesGanaderas20, on='Codigo Municipio')
HectareasGanaderas20 = ProvMun.merge(HectareasGanaderas20, on='Codigo Municipio')

In [10]:
ExplotacionesGanaderas20['Y2020'] = 2020
PrimeraColumna = ExplotacionesGanaderas20.pop('Y2020')
ExplotacionesGanaderas20.insert(0,'Y2020', PrimeraColumna)

In [11]:
ExplotacionesGanaderas20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Nº Explotaciones Ganaderas
0,2020,Araba/Álava,01,Agurain/Salvatierra,01051,40.0
1,2020,Araba/Álava,01,Alegría-Dulantzi,01001,17.0
2,2020,Araba/Álava,01,Amurrio,01002,113.0
3,2020,Araba/Álava,01,Añana,01049,11.0
4,2020,Araba/Álava,01,Aramaio,01003,61.0

In [12]:
HectareasGanaderas20['Y2020'] = 2020
PrimeraColumna = HectareasGanaderas20.pop('Y2020')
HectareasGanaderas20.insert(0,'Y2020', PrimeraColumna)

In [13]:
HectareasGanaderas20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Nº Hectareas Ganaderas
0,2020,Araba/Álava,01,Agurain/Salvatierra,01051,1785.07
1,2020,Araba/Álava,01,Alegría-Dulantzi,01001,942.54
2,2020,Araba/Álava,01,Amurrio,01002,2104.51
3,2020,Araba/Álava,01,Añana,01049,891.02
4,2020,Araba/Álava,01,Aramaio,01003,1090.04

In [14]:
ExplotacionesGanaderas20.to_excel('10_Output_Explotaciones_Ganaderas_20.xlsx', header = True, index = False)
HectareasGanaderas20.to_excel('10_Output_Hectareas_Ganaderas_20.xlsx', header = True, index = False)

### Explotaciones y hectáreas agrícolas 2010
Obtendremos un Dataframe con la siguiente información:
- Y2010
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio
- Nº Explotaciones Agricolas
- Nº Hectareas Agricolas

In [15]:
path = 'https://servicios.ine.es/wstempus/js/es/DATOS_TABLA/29006?tip=AM&'
json_request = requests.get(path).json()

In [16]:
CodExpList = list()
NumExpList = list()
CodSuperList = list()
NumSuperList = list()

In [17]:
for dato in json_request: 
    for i in range(0,len(dato['Data'])):
        if 'Nº explotaciones' in dato['Nombre']:
            CodExpList.append(dato['MetaData'][1]['Codigo'])
            NumExpList.append(dato['Data'][i]['Valor'])
        elif 'SAU (ha.)' in dato['Nombre']:
            CodSuperList.append(dato['MetaData'][1]['Codigo'])
            NumSuperList.append(dato['Data'][i]['Valor'])

In [18]:
ExplotacionesGanaderas10 = pd.DataFrame({
        'Codigo Municipio' : CodExpList,
        'Nº Explotaciones Ganaderas': NumExpList
    })
HectareasGanaderas10 = pd.DataFrame({
        'Codigo Municipio' : CodSuperList,
        'Nº Hectares Ganaderas': NumSuperList
    })

In [19]:
ExplotacionesGanaderas10.head()

  Codigo Municipio  Nº Explotaciones Ganaderas
0               01                      3691.0
1            01001                        20.0
2            01002                       215.0
3            01003                       101.0
4            01004                        58.0

In [20]:
HectareasGanaderas10.head()

  Codigo Municipio  Nº Hectares Ganaderas
0               01              102102.02
1            01001                1122.65
2            01002                4368.93
3            01003                1346.36
4            01004                1032.97

Cargamos la tabla 01_Output_ProvMun10.xlsx para posteriormente realizar el merge con ambos DataFrame:

In [21]:
ProvMun = pd.read_excel('01_Output_ProvMun_10.xlsx', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

In [22]:
ExplotacionesGanaderas10 = ProvMun.merge(ExplotacionesGanaderas10, on='Codigo Municipio')
HectareasGanaderas10 = ProvMun.merge(HectareasGanaderas10, on='Codigo Municipio')

In [23]:
ExplotacionesGanaderas10['Y2010'] = 2010
PrimeraColumna = ExplotacionesGanaderas10.pop('Y2010')
ExplotacionesGanaderas10.insert(0,'Y2010', PrimeraColumna)

In [24]:
ExplotacionesGanaderas10.head()

,Y2010,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Nº Explotaciones Ganaderas
0,2010,Araba/Álava,01,Agurain/Salvatierra,01051,51.0
1,2010,Araba/Álava,01,Alegría-Dulantzi,01001,20.0
2,2010,Araba/Álava,01,Amurrio,01002,215.0
3,2010,Araba/Álava,01,Añana,01049,15.0
4,2010,Araba/Álava,01,Aramaio,01003,101.0

In [25]:
HectareasGanaderas10['Y2010'] = 2010
PrimeraColumna = HectareasGanaderas10.pop('Y2010')
HectareasGanaderas10.insert(0,'Y2010', PrimeraColumna)

In [26]:
HectareasGanaderas10.head()

,Y2010,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Nº Hectares Ganaderas
0,2010,Araba/Álava,01,Agurain/Salvatierra,01051,1485.48
1,2010,Araba/Álava,01,Alegría-Dulantzi,01001,1122.65
2,2010,Araba/Álava,01,Amurrio,01002,4368.93
3,2010,Araba/Álava,01,Añana,01049,1202.24
4,2010,Araba/Álava,01,Aramaio,01003,1346.36

In [27]:
ExplotacionesGanaderas10.to_excel('10_Output_Explotaciones_Ganaderas_10.xlsx', header = True, index = False)
HectareasGanaderas10.to_excel('10_Output_Hectareas_Ganaderas_10.xlsx', header = True, index = False)