### Explotaciones ganaderas 2020

En este notebook procesaremos un JSON con el número de explotaciones bovinas, ovinas, porcinas y aves desagregado por municipios.

In [1]:
import pandas as pd
import requests

In [2]:
path = 'https://servicios.ine.es/wstempus/js/es/DATOS_TABLA/52076?tip=AM&'
json_request = requests.get(path).json()

In [3]:
CodBoniList = list()
NumBobiList = list()
CodOviList = list()
NumOviList = list()
CodPorciList = list()
NumPorciList = list()
CodAveList = list()
NumAveList = list()

In [4]:
for dato in json_request: 
    for i in range(0,len(dato['Data'])):
        if 'Bovinos, Nº explotaciones' in dato['Nombre']:
            CodBoniList.append(dato['MetaData'][0]['Codigo'])
            NumBobiList.append(dato['Data'][i]['Valor'])
        elif 'Ovino y caprino, Nº explotaciones' in dato['Nombre']:
            CodOviList.append(dato['MetaData'][0]['Codigo'])
            NumOviList.append(dato['Data'][i]['Valor'])
        elif 'Porcinos, Nº explotaciones' in dato['Nombre']:
            CodPorciList.append(dato['MetaData'][0]['Codigo'])
            NumPorciList.append(dato['Data'][i]['Valor']) 
        elif 'Aves de corral, Nº explotacione' in dato['Nombre']:
            CodAveList.append(dato['MetaData'][0]['Codigo'])
            NumAveList.append(dato['Data'][i]['Valor'])

In [5]:
ExplotacionesBovinas20 = pd.DataFrame({
        'Codigo Municipio' : CodBoniList,
        'Nº Explotaciones Bovinas': NumBobiList
    })
ExplotacionesOvinas20 = pd.DataFrame({
        'Codigo Municipio' : CodOviList,
        'Nº Explotaciones Ovinas': NumOviList
    })
ExplotacionesPorcinas20 = pd.DataFrame({
        'Codigo Municipio' : CodPorciList,
        'Nº Explotaciones Procinas': NumPorciList
    })
ExplotacionesAves20 = pd.DataFrame({
        'Codigo Municipio' : CodAveList,
        'Nº Explotaciones Aves': NumAveList
    })

In [6]:
ExplotacionesBovinas20.head()

  Codigo Municipio  Nº Explotaciones Bovinas
0               00                   90557.0
1               01                    5100.0
2               04                      33.0
3             0401                       5.0
4            04037                       0.0

In [7]:
ExplotacionesOvinas20.head()

  Codigo Municipio  Nº Explotaciones Ovinas
0               00                  72142.0
1               01                  13493.0
2               04                   1360.0
3             0401                    241.0
4            04037                     49.0

In [8]:
ExplotacionesPorcinas20.head()

  Codigo Municipio  Nº Explotaciones Procinas
0               00                    34673.0
1               01                     5324.0
2               04                      198.0
3             0401                       37.0
4            04037                        NaN

In [9]:
ExplotacionesAves20.head()

  Codigo Municipio  Nº Explotaciones Aves
0               00                18883.0
1               01                 1703.0
2               04                  195.0
3             0401                   31.0
4            04037                    4.0

Cargamos la tabla 01_Output_ProvMun20.xlsx para posteriormente realizar el merge con los anteriores DataFrame:

In [10]:
ProvMun = pd.read_excel('01_Output_ProvMun_20.xlsx', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

In [11]:
ExplotacionesBovinas20 = ProvMun.merge(ExplotacionesBovinas20, on='Codigo Municipio')
ExplotacionesOvinas20 = ProvMun.merge(ExplotacionesOvinas20, on='Codigo Municipio')
ExplotacionesPorcinas20 = ProvMun.merge(ExplotacionesPorcinas20, on='Codigo Municipio')
ExplotacionesAves20 = ProvMun.merge(ExplotacionesAves20, on='Codigo Municipio')

In [12]:
ExplotacionesBovinas20.head()

,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Nº Explotaciones Bovinas
0,Araba/Álava,01,Agurain/Salvatierra,01051,4.0
1,Araba/Álava,01,Alegría-Dulantzi,01001,0.0
2,Araba/Álava,01,Amurrio,01002,61.0
3,Araba/Álava,01,Añana,01049,NaN
4,Araba/Álava,01,Aramaio,01003,26.0

In [13]:
ExplotacionesOvinas20.head()

,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Nº Explotaciones Ovinas
0,Araba/Álava,01,Agurain/Salvatierra,01051,6.0
1,Araba/Álava,01,Alegría-Dulantzi,01001,4.0
2,Araba/Álava,01,Amurrio,01002,49.0
3,Araba/Álava,01,Añana,01049,NaN
4,Araba/Álava,01,Aramaio,01003,32.0

In [14]:
ExplotacionesPorcinas20.head()

,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Nº Explotaciones Procinas
0,Araba/Álava,01,Agurain/Salvatierra,01051,NaN
1,Araba/Álava,01,Alegría-Dulantzi,01001,NaN
2,Araba/Álava,01,Amurrio,01002,NaN
3,Araba/Álava,01,Añana,01049,NaN
4,Araba/Álava,01,Aramaio,01003,NaN

In [15]:
ExplotacionesAves20.head()

,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Nº Explotaciones Aves
0,Araba/Álava,01,Agurain/Salvatierra,01051,6.0
1,Araba/Álava,01,Alegría-Dulantzi,01001,NaN
2,Araba/Álava,01,Amurrio,01002,13.0
3,Araba/Álava,01,Añana,01049,0.0
4,Araba/Álava,01,Aramaio,01003,9.0

In [16]:
ExplotacionesBovinas20['Y2020'] = 2020
PrimeraColumna = ExplotacionesBovinas20.pop('Y2020')
ExplotacionesBovinas20.insert(0,'Y2020', PrimeraColumna)

In [17]:
ExplotacionesOvinas20['Y2020'] = 2020
PrimeraColumna = ExplotacionesOvinas20.pop('Y2020')
ExplotacionesOvinas20.insert(0,'Y2020', PrimeraColumna)

In [18]:
ExplotacionesPorcinas20['Y2020'] = 2020
PrimeraColumna = ExplotacionesPorcinas20.pop('Y2020')
ExplotacionesPorcinas20.insert(0,'Y2020', PrimeraColumna)

In [19]:
ExplotacionesAves20['Y2020'] = 2020
PrimeraColumna = ExplotacionesAves20.pop('Y2020')
ExplotacionesAves20.insert(0,'Y2020', PrimeraColumna)

In [20]:
ExplotacionesBovinas20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Nº Explotaciones Bovinas
0,2020,Araba/Álava,01,Agurain/Salvatierra,01051,4.0
1,2020,Araba/Álava,01,Alegría-Dulantzi,01001,0.0
2,2020,Araba/Álava,01,Amurrio,01002,61.0
3,2020,Araba/Álava,01,Añana,01049,NaN
4,2020,Araba/Álava,01,Aramaio,01003,26.0

In [21]:
ExplotacionesOvinas20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Nº Explotaciones Ovinas
0,2020,Araba/Álava,01,Agurain/Salvatierra,01051,6.0
1,2020,Araba/Álava,01,Alegría-Dulantzi,01001,4.0
2,2020,Araba/Álava,01,Amurrio,01002,49.0
3,2020,Araba/Álava,01,Añana,01049,NaN
4,2020,Araba/Álava,01,Aramaio,01003,32.0

In [22]:
ExplotacionesPorcinas20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Nº Explotaciones Procinas
0,2020,Araba/Álava,01,Agurain/Salvatierra,01051,NaN
1,2020,Araba/Álava,01,Alegría-Dulantzi,01001,NaN
2,2020,Araba/Álava,01,Amurrio,01002,NaN
3,2020,Araba/Álava,01,Añana,01049,NaN
4,2020,Araba/Álava,01,Aramaio,01003,NaN

In [23]:
ExplotacionesAves20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Nº Explotaciones Aves
0,2020,Araba/Álava,01,Agurain/Salvatierra,01051,6.0
1,2020,Araba/Álava,01,Alegría-Dulantzi,01001,NaN
2,2020,Araba/Álava,01,Amurrio,01002,13.0
3,2020,Araba/Álava,01,Añana,01049,0.0
4,2020,Araba/Álava,01,Aramaio,01003,9.0

In [24]:
ExplotacionesBovinas20.to_excel('11_Output_Explotaciones_Bovinas_20.xlsx', header = True, index = False)
ExplotacionesOvinas20.to_excel('11_Output__Explotaciones_Ovinas_20.xlsx', header = True, index = False)
ExplotacionesPorcinas20.to_excel('11_Output_Explotaciones_Porcinas_20.xlsx', header = True, index = False)
ExplotacionesAves20.to_excel('11_Output__Explotaciones_Aves_20.xlsx', header = True, index = False)