### Numero Empresas 2020

En este notebook procesaremos un .xlsx con el número de empresas desagregado por municipios y tipo de actividad.  
Obtendremos un DataFrame con la siguiente información:
- Y2020
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio
- Empresas Industria
- Empresas Construccion
- Empresas Comercio, Transporte y Hosteleria
- Empresas Informacion y Comunicacion
- Empresas Financieras y Seguros
- Empresas Inmobiliarias
- Empresas Profesionales y Tecnicas
- Empresas Educacion, Sanidad y Servicios Sociales
- Empresas Otros Servicios Personales
- Resto Empresas Servicios
- Total Empresas

In [1]:
import pandas as pd

In [2]:
NumeroEmpresas20 = pd.read_excel('12_Input_Numero_Empresas_20.xlsx', dtype='object')
NumeroEmpresas20.head()

,Municipios,Total,B_E Industria,F Construcción,"Comercio, transporte y hostelería",J Información y comunicaciones,K Actividades financieras y de seguros,L Actividades inmobiliarias,Actividades profesionales y técnicas,"Educación, sanidad y servicios sociales",Otros servicios personales,Total servicios
0,Total Nacional,3404428,195615,420118,1214123,69369,78851,186023,633069,284502,322758,1574572
1,01 Araba/Álava,18851,1885,2404,7098,370,325,233,3184,1558,1794,7464
2,01001 Alegría-Dulantzi,155,20,28,60,,,,,,,47
3,01002 Amurrio,601,60,101,247,6,8,4,91,44,40,193
4,01003 Aramaio,46,6,5,19,,,,,,,16

Cargamos la tabla 01_Output_ProvMun20.xlsx para posteriormente realizar el merge con NumeroEmpresas20:

In [3]:
ProvMun = pd.read_excel('01_Output_ProvMun_20.xlsx', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

Para realizar el marge, incluimos en la tabla NumeroEmpresas20 el campo Codigo Municipio:

In [4]:
MunList = ProvMun['Codigo Municipio'].tolist()

In [5]:
def check_list(x):
    for l in MunList:
        if l in x:
            return l
    return ''

In [6]:
NumeroEmpresas20['Codigo Municipio'] = NumeroEmpresas20['Municipios'].map(lambda x: check_list(x))

In [7]:
NumeroEmpresas20 = ProvMun.merge(NumeroEmpresas20, on='Codigo Municipio')
NumeroEmpresas20.head()

,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Municipios,Total,B_E Industria,F Construcción,"Comercio, transporte y hostelería",J Información y comunicaciones,K Actividades financieras y de seguros,L Actividades inmobiliarias,Actividades profesionales y técnicas,"Educación, sanidad y servicios sociales",Otros servicios personales,Total servicios
0,Araba/Álava,01,Agurain/Salvatierra,01051,01051 Agurain/Salvatierra,233,18,30,110,.,.,.,19,19,31,75
1,Araba/Álava,01,Alegría-Dulantzi,01001,01001 Alegría-Dulantzi,155,20,28,60,,,,,,,47
2,Araba/Álava,01,Amurrio,01002,01002 Amurrio,601,60,101,247,6,8,4,91,44,40,193
3,Araba/Álava,01,Añana,01049,01049 Añana,14,,,,,,,,,,
4,Araba/Álava,01,Aramaio,01003,01003 Aramaio,46,6,5,19,,,,,,,16

Creamos una columna con el año y renombramos los nombres de las variables:

In [8]:
NumeroEmpresas20['Y2020'] = 2020
PrimeraColumna = NumeroEmpresas20.pop('Y2020')
NumeroEmpresas20.insert(0,'Y2020', PrimeraColumna)
NumeroEmpresas20.rename({'B_E Industria' : 'Empresas Industria', 
                         'F Construcción':'Empresas Construccion',
                         'Comercio, transporte y hostelería' : 'Empresas Comercio Transporte y Hosteleria',
                         'J Información y comunicaciones' : 'Empresas Informacion y Comunicacion', 
                         'K Actividades financieras y de seguros' : 'Empresas Financieras y Seguros',
                         'L Actividades inmobiliarias' : 'Empresas Inmobiliarias',
                         'Actividades profesionales y técnicas' : 'Empresas Profesionales y Tecnicas',
                         'Educación, sanidad y servicios sociales' : 'Empresas Educacion Sanidad y Servicios Sociales',
                         'Otros servicios personales' : 'Empresas Otros Servicios Personales',
                         'Total servicios' : 'Resto Empresas Servicios'}, axis = 1, inplace = True)
NumeroEmpresas20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Municipios,Total,Empresas Industria,Empresas Construccion,Empresas Comercio Transporte y Hosteleria,Empresas Informacion y Comunicacion,Empresas Financieras y Seguros,Empresas Inmobiliarias,Empresas Profesionales y Tecnicas,Empresas Educacion Sanidad y Servicios Sociales,Empresas Otros Servicios Personales,Resto Empresas Servicios
0,2020,Araba/Álava,01,Agurain/Salvatierra,01051,01051 Agurain/Salvatierra,233,18,30,110,.,.,.,19,19,31,75
1,2020,Araba/Álava,01,Alegría-Dulantzi,01001,01001 Alegría-Dulantzi,155,20,28,60,,,,,,,47
2,2020,Araba/Álava,01,Amurrio,01002,01002 Amurrio,601,60,101,247,6,8,4,91,44,40,193
3,2020,Araba/Álava,01,Añana,01049,01049 Añana,14,,,,,,,,,,
4,2020,Araba/Álava,01,Aramaio,01003,01003 Aramaio,46,6,5,19,,,,,,,16

Añadimos una columna con el Total de Empresas: Sumamos la variable Total(suma de todas las variables menos Total Servicios) más la variable Total Servicios.  
El DataFrame contiene valores en blanco y valores con un punto. Lo substituimos por 0 para poder sumar.  
Cambiamos el formato de str a int.

In [9]:
NumeroEmpresas20 = NumeroEmpresas20.replace([' ', '.'], 0)
NumeroEmpresas20[['Total', 'Resto Empresas Servicios']] = NumeroEmpresas20[['Total', 'Resto Empresas Servicios']].astype(int)
NumeroEmpresas20['Total Empreas'] = NumeroEmpresas20['Total'] + NumeroEmpresas20['Resto Empresas Servicios']
NumeroEmpresas20.drop(['Municipios', 'Total'], axis = 1, inplace = True)
NumeroEmpresas20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Empresas Industria,Empresas Construccion,Empresas Comercio Transporte y Hosteleria,Empresas Informacion y Comunicacion,Empresas Financieras y Seguros,Empresas Inmobiliarias,Empresas Profesionales y Tecnicas,Empresas Educacion Sanidad y Servicios Sociales,Empresas Otros Servicios Personales,Resto Empresas Servicios,Total Empreas
0,2020,Araba/Álava,01,Agurain/Salvatierra,01051,18,30,110,0,0,0,19,19,31,75,308
1,2020,Araba/Álava,01,Alegría-Dulantzi,01001,20,28,60,0,0,0,0,0,0,47,202
2,2020,Araba/Álava,01,Amurrio,01002,60,101,247,6,8,4,91,44,40,193,794
3,2020,Araba/Álava,01,Añana,01049,0,0,0,0,0,0,0,0,0,0,14
4,2020,Araba/Álava,01,Aramaio,01003,6,5,19,0,0,0,0,0,0,16,62

In [10]:
NumeroEmpresas20.to_excel('12_Output_Numero_Empresas_20.xlsx', header = True, index = False)