## Numero establecimientos 2020 y 2010
En este notebook procesaremos un .xlsx con el número de establecimientos desagregado por municipios y por tipos de negocio: agricultura, industria, construcción y servicios.  
El .xlsx tiene dos hojas, una con los datos de 2020 y otra con los de 2010.

In [1]:
import pandas as pd
import numpy as np

### Numero establecimientos 2020
Obtendremos un DataFrame con la siguiente información:
- Y2020
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio
- Nº establecimientos Agricultura
- Nº establecimientos Industria
- Nº establecimientos Construccion
- Nº establecimientos Servicios

In [2]:
NumeroEstablecimientos20 = pd.read_excel('13_Input_Numero_Establecimientos_20_10.xlsx', '2020', dtype='object')
NumeroEstablecimientos20.head()

  Código          Etiqueta Agricultura Industria Construcción  Servicios
0  01001  Alegría-Dulantzi           2        13             9        58
1  01002           Amurrio          12        44            23       316
2  01003           Aramaio           1         5             1        20
3  01004        Artziniega           1         9             3        43
4  01006           Armiñón           0         2             1         2

Cargamos la tabla 01_Output_ProvMun20.xlsx para posteriormente realizar el merge con NumeroEstablecimientos20:

In [3]:
ProvMun = pd.read_excel('01_Output_ProvMun_20.xlsx', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

In [4]:
NumeroEstablecimientos20.rename({'Código':'Codigo Municipio'}, axis = 1, inplace = True)
NumeroEstablecimientos20=ProvMun.merge(NumeroEstablecimientos20, on='Codigo Municipio')
NumeroEstablecimientos20.head()

,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Etiqueta,Agricultura,Industria,Construcción,Servicios
0,Araba/Álava,01,Agurain/Salvatierra,01051,Salvatierra/Agurain,1,20,8,116
1,Araba/Álava,01,Alegría-Dulantzi,01001,Alegría-Dulantzi,2,13,9,58
2,Araba/Álava,01,Amurrio,01002,Amurrio,12,44,23,316
3,Araba/Álava,01,Añana,01049,Añana,0,1,1,9
4,Araba/Álava,01,Aramaio,01003,Aramaio,1,5,1,20

Añadimos la columna con el año 2020 y renombramos las variables:

In [5]:
NumeroEstablecimientos20['Y2020'] = 2020
PrimeraColumna = NumeroEstablecimientos20.pop('Y2020')
NumeroEstablecimientos20.insert(0,'Y2020', PrimeraColumna)
NumeroEstablecimientos20.rename({'Agricultura' : 'Nº Establecimientos Agricultura',
                                'Industria' : 'Nº Establecimientos Industria',
                                'Construcción ' : 'Nº Establecimientos Construccion', 
                                'Servicios' : 'Nº Establecimientos Servicios'}, axis = 1, inplace = True)
NumeroEstablecimientos20.drop(['Etiqueta'], axis = 1, inplace = True)
NumeroEstablecimientos20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Nº Establecimientos Agricultura,Nº Establecimientos Industria,Nº Establecimientos Construccion,Nº Establecimientos Servicios
0,2020,Araba/Álava,01,Agurain/Salvatierra,01051,1,20,8,116
1,2020,Araba/Álava,01,Alegría-Dulantzi,01001,2,13,9,58
2,2020,Araba/Álava,01,Amurrio,01002,12,44,23,316
3,2020,Araba/Álava,01,Añana,01049,0,1,1,9
4,2020,Araba/Álava,01,Aramaio,01003,1,5,1,20

Algunas variables toman el valor: N/A - resultado no disponible  
Lo substituimos por NaN:

In [6]:
NumeroEstablecimientos20.replace('N/A - resultado no disponible', np.nan, inplace = True)

In [7]:
NumeroEstablecimientos20.to_excel('13_Output_Numero_Establecimientos_20.xlsx', header = True, index = False)

### Numero establecimientos 2010

Obtendremos un DataFrame con la siguiente información:
- Y2010
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio
- Nº establecimientos Agricultura
- Nº establecimientos Industria
- Nº establecimientos Construccion
- Nº establecimientos Servicios

In [8]:
NumeroEstablecimientos10 = pd.read_excel('13_Input_Numero_Establecimientos_20_10.xlsx', '2010', dtype='object')
NumeroEstablecimientos10.head()

  Código          Etiqueta Agricultura Industria Construcción  Servicios
0  01001  Alegría-Dulantzi           0        17            12        62
1  01002           Amurrio           8        61            33       261
2  01003           Aramaio           3         4             3        12
3  01004        Artziniega           1        10             5        31
4  01006           Armiñón           0         3             0         4

Cargamos la tabla 01_Output_ProvMun10.xlsx para posteriormente realizar el merge con NumeroEstablecimientos10:

In [9]:
ProvMun = pd.read_excel('01_Output_ProvMun_10.xlsx', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

In [10]:
NumeroEstablecimientos10.rename({'Código':'Codigo Municipio'}, axis = 1, inplace = True)
NumeroEstablecimientos10=ProvMun.merge(NumeroEstablecimientos10, on='Codigo Municipio')
NumeroEstablecimientos10.head()

,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Etiqueta,Agricultura,Industria,Construcción,Servicios
0,Araba/Álava,01,Agurain/Salvatierra,01051,Salvatierra/Agurain,3,24,13,87
1,Araba/Álava,01,Alegría-Dulantzi,01001,Alegría-Dulantzi,0,17,12,62
2,Araba/Álava,01,Amurrio,01002,Amurrio,8,61,33,261
3,Araba/Álava,01,Añana,01049,Añana,0,1,1,4
4,Araba/Álava,01,Aramaio,01003,Aramaio,3,4,3,12

Añadimos la columna con el año 2010 y renombramos las variables:

In [11]:
NumeroEstablecimientos10['Y2010'] = 2010
PrimeraColumna = NumeroEstablecimientos10.pop('Y2010')
NumeroEstablecimientos10.insert(0,'Y2010', PrimeraColumna)
NumeroEstablecimientos10.rename({'Agricultura' : 'Nº Establecimientos Agricultura',
                                'Industria' : 'Nº Establecimientos Industria',
                                'Construcción ' : 'Nº Establecimientos Construccion', 
                                'Servicios' : 'Nº Establecimientos Servicios'}, axis = 1, inplace = True)
NumeroEstablecimientos10.drop(['Etiqueta'], axis = 1, inplace = True)
NumeroEstablecimientos10.head()

,Y2010,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Nº Establecimientos Agricultura,Nº Establecimientos Industria,Nº Establecimientos Construccion,Nº Establecimientos Servicios
0,2010,Araba/Álava,01,Agurain/Salvatierra,01051,3,24,13,87
1,2010,Araba/Álava,01,Alegría-Dulantzi,01001,0,17,12,62
2,2010,Araba/Álava,01,Amurrio,01002,8,61,33,261
3,2010,Araba/Álava,01,Añana,01049,0,1,1,4
4,2010,Araba/Álava,01,Aramaio,01003,3,4,3,12

Algunas variables toman el valor: N/A - resultado no disponible
Lo substituimos por NaN:

In [12]:
NumeroEstablecimientos10.replace('N/A - resultado no disponible', np.nan, inplace = True)

In [13]:
NumeroEstablecimientos10.to_excel('13_Output_Numero_Establecimientos_10.xlsx', header = True, index = False)