## Numero centros sanitarios 2020 y 2010
En este notebook procesaremos dos .xlsx; uno con el listado detallado de centros de salud y otro con el listado de hospialtes. Ambos desagregados por municipios.   
Cada uno de los .xlsx tiene dos hojas, una con los datos de 2020 y otra con los de 2010.

In [1]:
import pandas as pd

### Numero de centros sanitarios 2020
Obtendremos un DataFrame con la siguiente información:
- Y2020
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio
- Nº Centros Sanitarios

Procesamos el .xlsx de hospitales y de centros de salud del año 2020 y concatenamos:

In [2]:
NumeroHospitales20 = pd.read_excel('14_Input_Numero_Hospitales_20_10.xlsx', usecols = ['Nombre Centro', 'Cód. Municipio'], sheet_name ='2020', dtype='object')
NumeroHospitales20.head()

                                       Nombre Centro Cód. Municipio
0                                   HOSPITAL DE LEZA          01031
1                                  HOSPITAL SAN JOSE          01059
2                       HOSPITAL QUIRONSALUD VITORIA          01059
3                 HOSPITAL DE CUIDADOS SAN ONOFRE SL          01059
4  RED DE SALUD MENTAL DE ARABA (HOSPITAL PSIQUIA...          01059

In [3]:
NumeroCentrosSalud20 = pd.read_excel('14_Input_Numero_Centros_Salud_20_10.xlsx', usecols = ['      NOMBRE       ', '       CODMU       '], sheet_name ='2020', dtype='object')
NumeroCentrosSalud20.head()

         NOMBRE               CODMU
0   ALEGRﾍA-DULANTZI                 01001
1   AMURRIO                          01002
2   ARAMAIONA                        01003
3   ARTZINIEGA                       01004
4   DURANA                           01008

In [4]:
NumeroCentrosSalud20.rename({'      NOMBRE       ' : 'Nombre Centro', '       CODMU       ' : 'Cód. Municipio'}, axis = 1, inplace = True)

In [5]:
NumeroCentrosSanitarios20 = pd.concat([NumeroHospitales20, NumeroCentrosSalud20], ignore_index = True)
NumeroCentrosSanitarios20.head()

                                       Nombre Centro Cód. Municipio
0                                   HOSPITAL DE LEZA          01031
1                                  HOSPITAL SAN JOSE          01059
2                       HOSPITAL QUIRONSALUD VITORIA          01059
3                 HOSPITAL DE CUIDADOS SAN ONOFRE SL          01059
4  RED DE SALUD MENTAL DE ARABA (HOSPITAL PSIQUIA...          01059

Contamos cuántos centros sanitarios hay por municipio agrupando por Cód. Municipio:

In [6]:
NumeroCentrosSanitarios20 = NumeroCentrosSanitarios20.groupby('Cód. Municipio')['Nombre Centro'].count()
NumeroCentrosSanitarios20 = NumeroCentrosSanitarios20.reset_index()
NumeroCentrosSanitarios20.head()

  Cód. Municipio  Nombre Centro
0          01001              1
1          01002              1
2          01003              1
3          01004              1
4          01008              1

Cargamos la tabla 01_Output_ProvMun20.xlsx para posteriormente realizar el merge con NumeroCentrosSanitarios20:

In [7]:
ProvMun = pd.read_excel('01_Output_ProvMun_20.xlsx', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

In [8]:
NumeroCentrosSanitarios20.rename({'Cód. Municipio' : 'Codigo Municipio', 'Nombre Centro' : 'Nº Centros Sanitarios'}, axis = 1, inplace = True )
NumeroCentrosSanitarios20.head()

  Codigo Municipio  Nº Centros Sanitarios
0            01001                      1
1            01002                      1
2            01003                      1
3            01004                      1
4            01008                      1

In [9]:
NumeroCentrosSanitarios20 = ProvMun.merge(NumeroCentrosSanitarios20 , on='Codigo Municipio')
NumeroCentrosSanitarios20.head()

,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Nº Centros Sanitarios
0,Araba/Álava,01,Agurain/Salvatierra,01051,1
1,Araba/Álava,01,Alegría-Dulantzi,01001,1
2,Araba/Álava,01,Amurrio,01002,1
3,Araba/Álava,01,Añana,01049,1
4,Araba/Álava,01,Aramaio,01003,1

In [10]:
NumeroCentrosSanitarios20['Y2020'] = 2020
PrimeraColumna = NumeroCentrosSanitarios20.pop('Y2020')
NumeroCentrosSanitarios20.insert(0,'Y2020', PrimeraColumna)
NumeroCentrosSanitarios20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Nº Centros Sanitarios
0,2020,Araba/Álava,01,Agurain/Salvatierra,01051,1
1,2020,Araba/Álava,01,Alegría-Dulantzi,01001,1
2,2020,Araba/Álava,01,Amurrio,01002,1
3,2020,Araba/Álava,01,Añana,01049,1
4,2020,Araba/Álava,01,Aramaio,01003,1

In [11]:
NumeroCentrosSanitarios20.to_excel('14_Output_Numero_Centros_Sanitarios_20.xlsx', header = True, index = False)

### Numero de centros sanitarios 2010

Obtendremos un DataFrame con la siguiente información:
- Y2020
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio
- Nº Centros Sanitarios

Procesamos el .xlsx de hospitales y de centros de salud del año 2010 y concatenamos:

In [12]:
NumeroHospitales10 = pd.read_excel('14_Input_Numero_Hospitales_20_10.xlsx', usecols = ['NOMBRE', 'CODMU'], sheet_name ='2010', dtype='object')
NumeroHospitales10.head()

                                              NOMBRE  CODMU
0                               HOSPITAL TXAGORRITXU  01059
1                          HOSPITAL SANTIAGO APÓSTOL  01059
2  RED DE SALUD MENTAL DE ARABA (HOSPITAL PSIQUIÁ...  01059
3                                  HOSPITAL SAN JOSÉ  01059
4                          USP CLÍNICA  LA ESPERANZA  01059

In [13]:
NumeroCentrosSalud10 = pd.read_excel('14_Input_Numero_Centros_Salud_20_10.xlsx', usecols = ['NOMBRE', 'CODMU'], sheet_name ='2010', dtype='object')
NumeroCentrosSalud10.head()

       NOMBRE  CODMU
0    ALCALALÍ  03006
1      LLIBER  03085
2      SENIJA  03125
3  JALÓN/XALÓ  03081
4       CALPE  03047

In [14]:
NumeroCentrosSanitarios10 = pd.concat([NumeroHospitales10, NumeroCentrosSalud10], ignore_index = True)
NumeroCentrosSanitarios10.head()

                                              NOMBRE  CODMU
0                               HOSPITAL TXAGORRITXU  01059
1                          HOSPITAL SANTIAGO APÓSTOL  01059
2  RED DE SALUD MENTAL DE ARABA (HOSPITAL PSIQUIÁ...  01059
3                                  HOSPITAL SAN JOSÉ  01059
4                          USP CLÍNICA  LA ESPERANZA  01059

Contamos cuántos centros sanitarios hay por municipio agrupando por CODMU:

In [15]:
NumeroCentrosSanitarios10 = NumeroCentrosSanitarios10.groupby('CODMU')['NOMBRE'].count()
NumeroCentrosSanitarios10 = NumeroCentrosSanitarios10.reset_index()
NumeroCentrosSanitarios10.head()

   CODMU  NOMBRE
0  01001       1
1  01002       2
2  01003       1
3  01004       1
4  01008       1

Cargamos la tabla 01_Output_ProvMun10.xlsx para posteriormente realizar el merge con NumeroCentrosSanitarios10:

In [16]:
ProvMun = pd.read_excel('01_Output_ProvMun_10.xlsx', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

In [17]:
NumeroCentrosSanitarios10.rename({'CODMU' : 'Codigo Municipio', 'NOMBRE' : 'Nº Centros Sanitarios'}, axis = 1, inplace = True )
NumeroCentrosSanitarios10.head()

  Codigo Municipio  Nº Centros Sanitarios
0            01001                      1
1            01002                      2
2            01003                      1
3            01004                      1
4            01008                      1

In [18]:
NumeroCentrosSanitarios10 = ProvMun.merge(NumeroCentrosSanitarios10 , on='Codigo Municipio')
NumeroCentrosSanitarios10.head()

,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Nº Centros Sanitarios
0,Araba/Álava,01,Agurain/Salvatierra,01051,1
1,Araba/Álava,01,Alegría-Dulantzi,01001,1
2,Araba/Álava,01,Amurrio,01002,2
3,Araba/Álava,01,Añana,01049,1
4,Araba/Álava,01,Aramaio,01003,1

In [19]:
NumeroCentrosSanitarios10['Y2010'] = 2010
PrimeraColumna = NumeroCentrosSanitarios10.pop('Y2010')
NumeroCentrosSanitarios10.insert(0,'Y2010', PrimeraColumna)
NumeroCentrosSanitarios10.head()

,Y2010,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Nº Centros Sanitarios
0,2010,Araba/Álava,01,Agurain/Salvatierra,01051,1
1,2010,Araba/Álava,01,Alegría-Dulantzi,01001,1
2,2010,Araba/Álava,01,Amurrio,01002,2
3,2010,Araba/Álava,01,Añana,01049,1
4,2010,Araba/Álava,01,Aramaio,01003,1

In [20]:
NumeroCentrosSanitarios10.to_excel('14_Output_Numero_Centros_Sanitarios_10.xlsx', header = True, index = False)