## Numero de centros educativos 2020
En este notebook procesaremos un .xlsx  que contiene el listado detallado de centros educativos desagregados por municipios.  
Obtendremos un DataFrame con la siguiente información:
- Y2020
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio
- Nº Centros Educativos

In [1]:
import pandas as pd

In [2]:
CentrosEducativos20 = pd.read_excel('15_Input_Centros_Educativos_20.xlsx', 
                                    usecols = ['Denominación genérica', 'codigo ine'],
                                    dtype='object')
CentrosEducativos20.head()

  Denominación genérica codigo ine
0     AIURRI MONTESSORI      01059
1                EUROPA      01059
2   VERGE DE MONTI-SION      07043
3    VÉNDA D&apos;ARABÍ      07054
4          Ernest Lluch      08001

Contamos cuántos centros educativos hay por municipio agrupando por Codigo ine:

In [3]:
CentrosEducativos20 = CentrosEducativos20.groupby('codigo ine')['Denominación genérica'].count()
CentrosEducativos20 = CentrosEducativos20.reset_index()
CentrosEducativos20.head()

  codigo ine  Denominación genérica
0      01001                      4
1      01002                      9
2      01003                      2
3      01004                      3
4      01006                      2

Cargamos la tabla 01_Output_ProvMun20.xlsx para posteriormente realizar el merge con CentrosEducativos20:

In [4]:
ProvMun = pd.read_excel('01_Output_ProvMun_20.xlsx', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

In [5]:
CentrosEducativos20.rename({'codigo ine' : 'Codigo Municipio', 'Denominación genérica' : 'Nº Centros Educativos'}, axis = 1, inplace = True )
CentrosEducativos20.head()

  Codigo Municipio  Nº Centros Educativos
0            01001                      4
1            01002                      9
2            01003                      2
3            01004                      3
4            01006                      2

In [6]:
CentrosEducativos20 = ProvMun.merge(CentrosEducativos20 , on='Codigo Municipio')
CentrosEducativos20.head()

,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Nº Centros Educativos
0,Araba/Álava,01,Agurain/Salvatierra,01051,6
1,Araba/Álava,01,Alegría-Dulantzi,01001,4
2,Araba/Álava,01,Amurrio,01002,9
3,Araba/Álava,01,Aramaio,01003,2
4,Araba/Álava,01,Armiñón,01006,2

In [7]:
CentrosEducativos20['Y2020'] = 2020
PrimeraColumna = CentrosEducativos20.pop('Y2020')
CentrosEducativos20.insert(0,'Y2020', PrimeraColumna)
CentrosEducativos20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Nº Centros Educativos
0,2020,Araba/Álava,01,Agurain/Salvatierra,01051,6
1,2020,Araba/Álava,01,Alegría-Dulantzi,01001,4
2,2020,Araba/Álava,01,Amurrio,01002,9
3,2020,Araba/Álava,01,Aramaio,01003,2
4,2020,Araba/Álava,01,Armiñón,01006,2

In [8]:
CentrosEducativos20.to_excel('15_Output_Centros_Educativos_20.xlsx', header = True, index = False)