## Número de transacciones inmobiliarias 2020 y 2010
En este notebook procesaremos un .xlsx con el número de transacciones inmobiliarias de viviendas desagregado por municipios.  
El .xlsx tiene dos hojas, una con los datos de 2020 y otra con los de 2010.

### Numero de transacciones inmobiliarias 2020
Obtendremos un DataFrame con la siguiente información:
- Y2020
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio
- Nº Transacciones Inmobiliarias

Procesamos la hoja .xlsx correspondiente al año 2020:

In [1]:
import pandas as pd
import numpy as np

In [2]:
NumeroTransacciones20 = pd.read_excel('18_Input_Transacciones_Inmobiliarias_20_10.xlsx', sheet_name = '2020', dtype='object')
NumeroTransacciones20.head()

  Código          Etiqueta Número de transacciones anuales 2020
0  01001  Alegría-Dulantzi                                   31
1  01002           Amurrio                                   62
2  01003           Aramaio                                    4
3  01004        Artziniega                                   21
4  01006           Armiñón                                    0

Cargamos la tabla 01_Output_ProvMun20.xlsx para posteriormente realizar el merge con NumeroTransacciones20:

In [3]:
ProvMun = pd.read_excel('01_Output_ProvMun_20.xlsx', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

In [4]:
NumeroTransacciones20.rename({'Código' : 'Codigo Municipio', 
                              'Número de transacciones anuales 2020' : 'Nº de transacciones'}, axis = 1, inplace = True)

In [5]:
NumeroTransacciones20 = ProvMun.merge(NumeroTransacciones20, on='Codigo Municipio')
NumeroTransacciones20.head()

,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Etiqueta,Nº de transacciones
0,Araba/Álava,01,Agurain/Salvatierra,01051,Salvatierra/Agurain,39
1,Araba/Álava,01,Alegría-Dulantzi,01001,Alegría-Dulantzi,31
2,Araba/Álava,01,Amurrio,01002,Amurrio,62
3,Araba/Álava,01,Añana,01049,Añana,4
4,Araba/Álava,01,Aramaio,01003,Aramaio,4

Eliminamos la variable Etiqueta e incluimos una columna con el año 2020:

In [6]:
NumeroTransacciones20.drop(['Etiqueta'], axis = 1, inplace = True)
NumeroTransacciones20['Y2020'] = 2020
PrimeraColumna = NumeroTransacciones20.pop('Y2020')
NumeroTransacciones20.insert(0,'Y2020', PrimeraColumna)
NumeroTransacciones20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Nº de transacciones
0,2020,Araba/Álava,01,Agurain/Salvatierra,01051,39
1,2020,Araba/Álava,01,Alegría-Dulantzi,01001,31
2,2020,Araba/Álava,01,Amurrio,01002,62
3,2020,Araba/Álava,01,Añana,01049,4
4,2020,Araba/Álava,01,Aramaio,01003,4

Algunas variables toman el valor: N/A - resultado no disponible.  
Lo substituimos por NaN:

In [7]:
NumeroTransacciones20.replace('N/A - resultado no disponible', np.nan, inplace = True)

In [8]:
NumeroTransacciones20.to_excel('18_Output_Numero_Transacciones_20.xlsx', header = True, index = False)

### Numero de transacciones inmobiliarias 2010

Obtendremos un DataFrame con la siguiente información:
- Y2010
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio
- Nº Transacciones Inmobiliarias

Procesamos la hoja .xlsx correspondiente al año 2010:

In [9]:
NumeroTransacciones10 = pd.read_excel('18_Input_Transacciones_Inmobiliarias_20_10.xlsx', sheet_name = '2010', dtype='object')
NumeroTransacciones10.head()

  Código          Etiqueta Número de transacciones anuales 2010
0  01001  Alegría-Dulantzi                                   32
1  01002           Amurrio                                   57
2  01003           Aramaio                                    1
3  01004        Artziniega                                    7
4  01006           Armiñón                                    4

Cargamos la tabla 01_Output_ProvMun10.xlsx para posteriormente realizar el merge con NumeroTransacciones10:

In [10]:
ProvMun = pd.read_excel('01_Output_ProvMun_10.xlsx', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

In [11]:
NumeroTransacciones10.rename({'Código' : 'Codigo Municipio', 
                              'Número de transacciones anuales 2010' : 'Nº de transacciones'}, axis = 1, inplace = True)

In [12]:
NumeroTransacciones10 = ProvMun.merge(NumeroTransacciones10, on='Codigo Municipio')
NumeroTransacciones10.head()

,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Etiqueta,Nº de transacciones
0,Araba/Álava,01,Agurain/Salvatierra,01051,Salvatierra/Agurain,44
1,Araba/Álava,01,Alegría-Dulantzi,01001,Alegría-Dulantzi,32
2,Araba/Álava,01,Amurrio,01002,Amurrio,57
3,Araba/Álava,01,Añana,01049,Añana,1
4,Araba/Álava,01,Aramaio,01003,Aramaio,1

Eliminamos la variable Etiqueta e incluimos una columna con el año 2010:

In [13]:
NumeroTransacciones10.drop(['Etiqueta'], axis = 1, inplace = True)
NumeroTransacciones10['Y2010'] = 2010
PrimeraColumna = NumeroTransacciones10.pop('Y2010')
NumeroTransacciones10.insert(0,'Y2010', PrimeraColumna)
NumeroTransacciones10.head()

,Y2010,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Nº de transacciones
0,2010,Araba/Álava,01,Agurain/Salvatierra,01051,44
1,2010,Araba/Álava,01,Alegría-Dulantzi,01001,32
2,2010,Araba/Álava,01,Amurrio,01002,57
3,2010,Araba/Álava,01,Añana,01049,1
4,2010,Araba/Álava,01,Aramaio,01003,1

Algunas variables toman el valor: N/A - resultado no disponible.  
Lo substituimos por NaN:

In [14]:
NumeroTransacciones10.replace('N/A - resultado no disponible', np.nan, inplace = True)

In [15]:
NumeroTransacciones10.to_excel('18_Output_Numero_Transacciones_10.xlsx', header = True, index = False)