## Edad medida de los edificios 2020 y 2010
En este notebook procesaremos un .xlsx con la edad media de los edificios por municipios.  
El .xlsx tiene dos hojas, una con los datos de 2020 y otra con los de 2010.

In [1]:
import pandas as pd
import numpy as np

### Edad medida de los edificios 2020
Obtendremos un DataFrame con la siguiente información:
- Y2020
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio
- Edad Media Edificios

Procesamos la hoja .xlsx correspondiente al año 2020:

In [2]:
EdadEdificios20 = pd.read_excel('19_Input_Edad_Edificios_20_10.xlsx', sheet_name = '2020', dtype='object')
EdadEdificios20.head()

  Código          Etiqueta Edad media de los edificios 2020
0  01001  Alegría-Dulantzi    N/A - resultado no disponible
1  01002           Amurrio    N/A - resultado no disponible
2  01003           Aramaio    N/A - resultado no disponible
3  01004        Artziniega    N/A - resultado no disponible
4  01006           Armiñón    N/A - resultado no disponible

Cargamos la tabla 01_Output_ProvMun20.xlsx para posteriormente realizar el merge con EdadEdificios20:

In [3]:
ProvMun = pd.read_excel('01_Output_ProvMun_20.xlsx', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

In [4]:
EdadEdificios20.rename({'Código':'Codigo Municipio', 'Edad media de los edificios 2020' : 'Edad Media Edificios'}, axis = 1, inplace = True)

In [5]:
EdadEdificios20 = ProvMun.merge(EdadEdificios20, on='Codigo Municipio')
EdadEdificios20.head()

,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Etiqueta,Edad Media Edificios
0,Araba/Álava,01,Agurain/Salvatierra,01051,Salvatierra/Agurain,N/A - resultado no disponible
1,Araba/Álava,01,Alegría-Dulantzi,01001,Alegría-Dulantzi,N/A - resultado no disponible
2,Araba/Álava,01,Amurrio,01002,Amurrio,N/A - resultado no disponible
3,Araba/Álava,01,Añana,01049,Añana,N/A - resultado no disponible
4,Araba/Álava,01,Aramaio,01003,Aramaio,N/A - resultado no disponible

Eliminamos la variable Etiqueta e incluimos una columna con el año 2020:

In [6]:
EdadEdificios20.drop(['Etiqueta'], axis = 1, inplace = True)
EdadEdificios20['Y2020'] = 2020
PrimeraColumna = EdadEdificios20.pop('Y2020')
EdadEdificios20.insert(0,'Y2020', PrimeraColumna)
EdadEdificios20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Edad Media Edificios
0,2020,Araba/Álava,01,Agurain/Salvatierra,01051,N/A - resultado no disponible
1,2020,Araba/Álava,01,Alegría-Dulantzi,01001,N/A - resultado no disponible
2,2020,Araba/Álava,01,Amurrio,01002,N/A - resultado no disponible
3,2020,Araba/Álava,01,Añana,01049,N/A - resultado no disponible
4,2020,Araba/Álava,01,Aramaio,01003,N/A - resultado no disponible

Algunas variables toman el valor: N/A - resultado no disponible.  
Lo substituimos por NaN:

In [7]:
EdadEdificios20.replace('N/A - resultado no disponible', np.nan, inplace = True)

In [8]:
EdadEdificios20.to_excel('19_Output_Edad_Edificios_20.xlsx', header = True, index = False)

### Edad medida de los edificios 2010
Obtendremos un DataFrame con la siguiente información:
- Y2010
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio
- Edad Media Edificios

Procesamos la hoja .xlsx correspondiente al año 2010:

In [9]:
EdadEdificios10 = pd.read_excel('19_Input_Edad_Edificios_20_10.xlsx', sheet_name = '2010', dtype='object')
EdadEdificios10.head()

  Código          Etiqueta Edad media de los edificios 2010
0  01001  Alegría-Dulantzi    N/A - resultado no disponible
1  01002           Amurrio    N/A - resultado no disponible
2  01003           Aramaio    N/A - resultado no disponible
3  01004        Artziniega    N/A - resultado no disponible
4  01006           Armiñón    N/A - resultado no disponible

Cargamos la tabla 01_Output_ProvMun10.xlsx para posteriormente realizar el merge con EdadEdificios10:

In [10]:
ProvMun = pd.read_excel('01_Output_ProvMun_10.xlsx', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

In [11]:
EdadEdificios10.rename({'Código':'Codigo Municipio', 'Edad media de los edificios 2010' : 'Edad Media Edificios'}, axis = 1, inplace = True)

In [12]:
EdadEdificios10 = ProvMun.merge(EdadEdificios10, on='Codigo Municipio')
EdadEdificios10.head()

,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Etiqueta,Edad Media Edificios
0,Araba/Álava,01,Agurain/Salvatierra,01051,Salvatierra/Agurain,N/A - resultado no disponible
1,Araba/Álava,01,Alegría-Dulantzi,01001,Alegría-Dulantzi,N/A - resultado no disponible
2,Araba/Álava,01,Amurrio,01002,Amurrio,N/A - resultado no disponible
3,Araba/Álava,01,Añana,01049,Añana,N/A - resultado no disponible
4,Araba/Álava,01,Aramaio,01003,Aramaio,N/A - resultado no disponible

Eliminamos la variable Etiqueta e incluimos una columna con el año 2010:

In [13]:
EdadEdificios10.drop(['Etiqueta'], axis = 1, inplace = True)
EdadEdificios10['Y2010'] = 2010
PrimeraColumna = EdadEdificios10.pop('Y2010')
EdadEdificios10.insert(0,'Y2010', PrimeraColumna)
EdadEdificios10.head()

,Y2010,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Edad Media Edificios
0,2010,Araba/Álava,01,Agurain/Salvatierra,01051,N/A - resultado no disponible
1,2010,Araba/Álava,01,Alegría-Dulantzi,01001,N/A - resultado no disponible
2,2010,Araba/Álava,01,Amurrio,01002,N/A - resultado no disponible
3,2010,Araba/Álava,01,Añana,01049,N/A - resultado no disponible
4,2010,Araba/Álava,01,Aramaio,01003,N/A - resultado no disponible

Algunas variables toman el valor: N/A - resultado no disponible.  
Lo substituimos por NaN:

In [14]:
EdadEdificios10.replace('N/A - resultado no disponible', np.nan, inplace = True)

In [15]:
EdadEdificios10.to_excel('19_Output_Edad_Edificios_10.xlsx', header = True, index = False)