## Uso del suelo 2020 y 2010

En este notebook procesaremos un .xlsx con el número de hectáreas de uso del suelo; industrial, residencial, terciario y otros, desagregao por municipios.  
El .xlsx tiene dos hojas, una con los datos de 2020 y otra con los de 2010.

In [1]:
import pandas as pd
import numpy as np

### Uso del suelo 2020
Obtendremos un DataFrame con la siguiente información:
- Y2020
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio
- Otros Usos
- Uso Industrial
- Uso Residelcial
- Uso Terciario

Procesamos la hoja .xlsx correspondiente al año 2020:

In [2]:
UsoSuelo20 = pd.read_excel('20_Input_Uso_Suelo_20_10.xlsx', sheet_name = '2020', dtype='object')
UsoSuelo20.head()

,Código,Etiqueta,Otros usos 2020,"Uso industrial, almacenamiento y estacionamiento 2020",Uso residencial 2020,Uso terciario 2020
0,01001,Alegría-Dulantzi,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible
1,01002,Amurrio,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible
2,01003,Aramaio,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible
3,01004,Artziniega,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible
4,01006,Armiñón,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible

Cargamos la tabla 01_Output_ProvMun20.xlsx para posteriormente realizar el merge con UsoSuelo20:

In [3]:
ProvMun = pd.read_excel('01_Output_ProvMun_20.xlsx', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

In [4]:
UsoSuelo20.rename({'Código':'Codigo Municipio',
                  'Otros usos 2020' : 'Otros Usos',
                  'Uso industrial, almacenamiento y estacionamiento 2020' : 'Uso Industrial',
                  'Uso residencial 2020' : 'Uso Residelcial',
                  'Uso terciario 2020' : 'Uso Terciario'}, axis = 1, inplace = True)

In [5]:
UsoSuelo20 = ProvMun.merge(UsoSuelo20, on='Codigo Municipio')
UsoSuelo20.head()

,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Etiqueta,Otros Usos,Uso Industrial,Uso Residelcial,Uso Terciario
0,Araba/Álava,01,Agurain/Salvatierra,01051,Salvatierra/Agurain,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible
1,Araba/Álava,01,Alegría-Dulantzi,01001,Alegría-Dulantzi,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible
2,Araba/Álava,01,Amurrio,01002,Amurrio,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible
3,Araba/Álava,01,Añana,01049,Añana,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible
4,Araba/Álava,01,Aramaio,01003,Aramaio,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible

Eliminamos la variable Etiqueta e incluimos una columna con el año 2020:

In [6]:
UsoSuelo20.drop(['Etiqueta'], axis = 1, inplace = True)
UsoSuelo20['Y2020'] = 2020
PrimeraColumna = UsoSuelo20.pop('Y2020')
UsoSuelo20.insert(0,'Y2020', PrimeraColumna)
UsoSuelo20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Otros Usos,Uso Industrial,Uso Residelcial,Uso Terciario
0,2020,Araba/Álava,01,Agurain/Salvatierra,01051,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible
1,2020,Araba/Álava,01,Alegría-Dulantzi,01001,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible
2,2020,Araba/Álava,01,Amurrio,01002,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible
3,2020,Araba/Álava,01,Añana,01049,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible
4,2020,Araba/Álava,01,Aramaio,01003,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible

Algunas variables toman el valor: N/A - resultado no disponible.  
Lo substituimos por NaN:

In [7]:
UsoSuelo20.replace('N/A - resultado no disponible', np.nan, inplace = True)

In [8]:
UsoSuelo20.to_excel('20_Output_Uso_Suelo_20.xlsx', header = True, index = False)

### Uso del suelo 2010
Obtendremos un DataFrame con la siguiente información:
- Y2010
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio
- Otros Usos
- Uso Industrial
- Uso Residelcial
- Uso Terciario

Procesamos la hoja .xlsx correspondiente al año 2010:

In [9]:
UsoSuelo10 = pd.read_excel('20_Input_Uso_Suelo_20_10.xlsx', sheet_name = '2010', dtype='object')
UsoSuelo10.head()

,Código,Etiqueta,Otros usos 2010,"Uso industrial, almacenamiento y estacionamiento 2010",Uso residencial 2010,Uso terciario 2010
0,01001,Alegría-Dulantzi,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible
1,01002,Amurrio,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible
2,01003,Aramaio,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible
3,01004,Artziniega,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible
4,01006,Armiñón,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible

Cargamos la tabla 01_Output_ProvMun10.xlsx para posteriormente realizar el merge con UsoSuelo10:

In [10]:
ProvMun = pd.read_excel('01_Output_ProvMun_10.xlsx', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

In [11]:
UsoSuelo10.rename({'Código':'Codigo Municipio',
                  'Otros usos 2010' : 'Otros Usos',
                  'Uso industrial, almacenamiento y estacionamiento 2010' : 'Uso Industrial',
                  'Uso residencial 2010' : 'Uso Residelcial',
                  'Uso terciario 2010' : 'Uso Terciario'}, axis = 1, inplace = True)

In [12]:
UsoSuelo10 = ProvMun.merge(UsoSuelo10, on='Codigo Municipio')
UsoSuelo10.head()

,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Etiqueta,Otros Usos,Uso Industrial,Uso Residelcial,Uso Terciario
0,Araba/Álava,01,Agurain/Salvatierra,01051,Salvatierra/Agurain,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible
1,Araba/Álava,01,Alegría-Dulantzi,01001,Alegría-Dulantzi,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible
2,Araba/Álava,01,Amurrio,01002,Amurrio,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible
3,Araba/Álava,01,Añana,01049,Añana,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible
4,Araba/Álava,01,Aramaio,01003,Aramaio,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible

Eliminamos la variable Etiqueta e incluimos una columna con el año 2010:

In [13]:
UsoSuelo10.drop(['Etiqueta'], axis = 1, inplace = True)
UsoSuelo10['Y2010'] = 2010
PrimeraColumna = UsoSuelo10.pop('Y2010')
UsoSuelo10.insert(0,'Y2010', PrimeraColumna)
UsoSuelo10.head()

,Y2010,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Otros Usos,Uso Industrial,Uso Residelcial,Uso Terciario
0,2010,Araba/Álava,01,Agurain/Salvatierra,01051,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible
1,2010,Araba/Álava,01,Alegría-Dulantzi,01001,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible
2,2010,Araba/Álava,01,Amurrio,01002,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible
3,2010,Araba/Álava,01,Añana,01049,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible
4,2010,Araba/Álava,01,Aramaio,01003,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible,N/A - resultado no disponible

Algunas variables toman el valor: N/A - resultado no disponible.  
Lo substituimos por NaN:

In [14]:
UsoSuelo10.replace('N/A - resultado no disponible', np.nan, inplace = True)

In [15]:
UsoSuelo10.to_excel('20_Output_Uso_Suelo_10.xlsx', header = True, index = False)