## Numero de conductores, vehículos y su antigüedad 2020
En este notebook procesaremos un .xlsx que contiene el número de conductores; hombres y mujeres, número de vehículos y su antigüedad media.  
Los datos están desagregados por municipios.  
Obtendremos un DataFrame con la siguiente información:
- Y2020
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio
- Conductores Hombres
- Conductoras Mujeres
- Censo Conductores
- Parque Total
- Antigüedad Media

In [1]:
import pandas as pd

In [2]:
Vehiculos20 = pd.read_excel('21_Input_Vehiculos_20.xlsx', 
                                    usecols = ['Código INE',
                                               'Conductores Hombres', 
                                               'Conductoras Mujeres', 
                                               'Censo Conductores', 
                                              'Parque Total',
                                              'Antigüedad Media'],
                                    dtype='object')
Vehiculos20.head()

,Código INE,Conductores Hombres,Conductoras Mujeres,Censo Conductores,Parque Total,Antigüedad Media
0,01000,1,NaN,1,8,18.556667
1,01001,1038,818,1856,2031,12.819203
2,01002,3664,2660,6324,6790,13.529362
3,01003,566,425,991,1199,13.333228
4,01004,630,490,1120,1345,14.450531

Cargamos la tabla 01_Output_ProvMun20.xlsx para posteriormente realizar el merge con Vehiculos20:

In [3]:
ProvMun = pd.read_excel('01_Output_ProvMun_20.xlsx', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

In [4]:
Vehiculos20.rename({'Código INE' : 'Codigo Municipio'}, axis = 1, inplace = True )
Vehiculos20.head()

,Codigo Municipio,Conductores Hombres,Conductoras Mujeres,Censo Conductores,Parque Total,Antigüedad Media
0,01000,1,NaN,1,8,18.556667
1,01001,1038,818,1856,2031,12.819203
2,01002,3664,2660,6324,6790,13.529362
3,01003,566,425,991,1199,13.333228
4,01004,630,490,1120,1345,14.450531

In [5]:
Vehiculos20 = ProvMun.merge(Vehiculos20 , on='Codigo Municipio')
Vehiculos20.head()

,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Conductores Hombres,Conductoras Mujeres,Censo Conductores,Parque Total,Antigüedad Media
0,Araba/Álava,01,Agurain/Salvatierra,01051,1728,1217,2945,3366,13.72621
1,Araba/Álava,01,Alegría-Dulantzi,01001,1038,818,1856,2031,12.819203
2,Araba/Álava,01,Amurrio,01002,3664,2660,6324,6790,13.529362
3,Araba/Álava,01,Añana,01049,49,24,73,148,14.817438
4,Araba/Álava,01,Aramaio,01003,566,425,991,1199,13.333228

Añadimos una columna con el año 2020:

In [6]:
Vehiculos20['Y2020'] = 2020
PrimeraColumna = Vehiculos20.pop('Y2020')
Vehiculos20.insert(0,'Y2020', PrimeraColumna)
Vehiculos20.head()

,Y2020,Nombre Provincia,Codigo Provincia,Nombre Municipio,Codigo Municipio,Conductores Hombres,Conductoras Mujeres,Censo Conductores,Parque Total,Antigüedad Media
0,2020,Araba/Álava,01,Agurain/Salvatierra,01051,1728,1217,2945,3366,13.72621
1,2020,Araba/Álava,01,Alegría-Dulantzi,01001,1038,818,1856,2031,12.819203
2,2020,Araba/Álava,01,Amurrio,01002,3664,2660,6324,6790,13.529362
3,2020,Araba/Álava,01,Añana,01049,49,24,73,148,14.817438
4,2020,Araba/Álava,01,Aramaio,01003,566,425,991,1199,13.333228

In [7]:
Vehiculos20.to_excel('21_Output_Vehiculos_20.xlsx', header = True, index = False)