## Códigos provincias y municipios 2011 y 2021
En  este notebook procesaremos dos .xlsx con la relación de provincias y municipios con sus códigos del INE.  
Uno de ellos es relativo al año 2011 y el otro al año 2021.  
Obtendremos dos DataFrame con la siguiente información:
- Nombre Provincia
- Codigo Provincia
- Nombre Municipio
- Codigo Municipio: se compone de cinco dígitos, los dos primeros corresponden al código de la provincia y los tres restantes al del municipio dentro de ésta

In [1]:
import pandas as pd

Tabla que relaciona códigos de provincias y municipios en 2011:

In [2]:
ProvMun = pd.read_excel('01_Input_ProvMun_11.xlsx', dtype={'CPRO' : str, 'CMUN' : str})

ProvMun['Codigo Municipio'] = ProvMun['CPRO'].map(str)+ProvMun['CMUN'].map(str)

ProvMun = ProvMun.drop(['CODAUTO','CMUN','DC'], axis=1)

ProvMun.rename({'CPRO': 'Codigo Provincia', 
                'NOMBREPRO':'Nombre Provincia',
                'NOMBREMUN': 'Nombre Municipio' }, axis=1, inplace=True)

ProvMun = ProvMun.reindex(columns=['Nombre Provincia','Codigo Provincia','Nombre Municipio','Codigo Municipio'])

ProvMun.head()

  Nombre Provincia Codigo Provincia  Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Alegría-Dulantzi            01001
1      Araba/Álava               01           Amurrio            01002
2      Araba/Álava               01             Añana            01049
3      Araba/Álava               01           Aramaio            01003
4      Araba/Álava               01           Armiñón            01006

In [3]:
ProvMun.to_csv('01_Output_ProvMun_11.csv', header = True, index = False)

Tabla que relaciona códigos de provincias y municipios en 2021:

In [4]:
ProvMun = pd.read_excel('01_Input_ProvMun_21.xlsx', dtype={'CPRO' : str, 'CMUN' : str}) 

ProvMun['Codigo Municipio'] = ProvMun['CPRO'].map(str)+ProvMun['CMUN'].map(str)

ProvMun = ProvMun.drop(['CODAUTO','CMUN','DC'], axis=1)

ProvMun.rename({'CPRO': 'Codigo Provincia', 
                'NOMBREPRO':'Nombre Provincia',
                'NOMBREMUN': 'Nombre Municipio' }, axis=1, inplace=True)

ProvMun = ProvMun.reindex(columns=['Nombre Provincia','Codigo Provincia','Nombre Municipio','Codigo Municipio'])

ProvMun.head()

  Nombre Provincia Codigo Provincia     Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Agurain/Salvatierra            01051
1      Araba/Álava               01     Alegría-Dulantzi            01001
2      Araba/Álava               01              Amurrio            01002
3      Araba/Álava               01                Añana            01049
4      Araba/Álava               01              Aramaio            01003

In [5]:
ProvMun.to_csv('01_Output_ProvMun_21.csv', header = True, index = False)