## Parados 2011
En este notebook procesaremos un .xlsx que contiene el paro registrado por municipios, sexo, edad; <25, 25-45, >=45, y sector de actividad económica; agricultura, industria, construcción, servicios y parados de larga duración.  

Obtendremos un DataFrame con la siguiente información:
- Codigo Municipio
- Paro hombre edad < 25
- Paro hombre edad 25-45
- Paro hombre edad >=45
- Paro mujer edad < 25
- Paro mujer edad 25-45
- Paro mujer edad >=45
- Paro Agricultura
- Paro Industria
- Paro Construcción
- Paro Servicios
- Paro Sin empleo Anterior

In [1]:
import pandas as pd

In [2]:
Parados11 = pd.read_excel('08_Input_Parados_11.xlsx',dtype='object')
Parados11.head()

,Codigo Municipio,Municipio,Suma de total Paro Registrado,Suma de Paro hombre edad < 25,Suma de Paro hombre edad 25 -45,Suma de Paro hombre edad >=45,Suma de Paro mujer edad < 25,Suma de Paro mujer edad 25 -45,Suma de Paro mujer edad >=45,Suma de Paro Agricultura,Suma de Paro Industria,Suma de Paro Construcción,Suma de Paro Servicios,Suma de Paro Sin empleo Anterior
0,01001,Alegría-Dulantzi,1992,86,552,297,97,737,223,35,444,149,1237,127
1,01002,Amurrio,8393,535,1816,1391,337,2243,2071,130,1683,941,5036,603
2,01003,Aramaio,322,2,69,106,5,79,61,0,146,3,160,13
3,01004,Artziniega,1690,101,413,216,59,607,294,23,323,132,1091,121
4,01006,Armiñón,139,5,45,10,3,44,32,0,39,21,79,0

In [3]:
Parados11.drop([' Municipio'], axis=1, inplace=True)
Parados11.head()

,Codigo Municipio,Suma de total Paro Registrado,Suma de Paro hombre edad < 25,Suma de Paro hombre edad 25 -45,Suma de Paro hombre edad >=45,Suma de Paro mujer edad < 25,Suma de Paro mujer edad 25 -45,Suma de Paro mujer edad >=45,Suma de Paro Agricultura,Suma de Paro Industria,Suma de Paro Construcción,Suma de Paro Servicios,Suma de Paro Sin empleo Anterior
0,01001,1992,86,552,297,97,737,223,35,444,149,1237,127
1,01002,8393,535,1816,1391,337,2243,2071,130,1683,941,5036,603
2,01003,322,2,69,106,5,79,61,0,146,3,160,13
3,01004,1690,101,413,216,59,607,294,23,323,132,1091,121
4,01006,139,5,45,10,3,44,32,0,39,21,79,0

In [4]:
Parados11.to_csv('08_Output_Parados_11.csv', header = True, index = False)