## Edades 2011
En este notebook procesaremos un .xlsx con el número de personas segun su situacion civil desagregado por municipios.  

Obtendremos un DataFrame con la siguiente información:
- Codigo Municipio
- Soltero/a 	
- Casado/a
- Separado/a
- Divorciado/a
- Viudo/a

In [1]:
import pandas as pd

In [2]:
EstadoCivil11 = pd.read_excel('19_Input_Estado_Civil_11.xlsx', dtype='object')
EstadoCivil11.head()

  Municipio de residencia Soltero/a Casado/a Separado/a Divorciado/a Viudo/a
0            44001 Ababuj        30       35          *            *       *
1            40001 Abades       390      400          *            *      80
2            10001 Abadía       140      170          *            *      10
3            27001 Abadín       965     1355          *           60     370
4           48001 Abadiño      3165     3685          *           95     345

Añadimos el campo Código Municipio al DataFrame asignando el valor de cada fila en función del código que aparece en el campo municipio de residencia.  
Para ello usamos la tabla 01_Output_ProvMun_11.csv que contiene los códigos por municipio:

In [3]:
ProvMun = pd.read_csv('01_Output_ProvMun_11.csv', dtype='object') 
ProvMun.head()

  Nombre Provincia Codigo Provincia  Nombre Municipio Codigo Municipio
0      Araba/Álava               01  Alegría-Dulantzi            01001
1      Araba/Álava               01           Amurrio            01002
2      Araba/Álava               01             Añana            01049
3      Araba/Álava               01           Aramaio            01003
4      Araba/Álava               01           Armiñón            01006

In [4]:
MunList = ProvMun['Codigo Municipio'].tolist()

In [5]:
def check_list(x):
    for l in MunList:
        if l in x:
            return l
    return ''

In [6]:
EstadoCivil11['Codigo Municipio'] = EstadoCivil11['Municipio de residencia'].map(lambda x: check_list(x))
EstadoCivil11.head()

,Municipio de residencia,Soltero/a,Casado/a,Separado/a,Divorciado/a,Viudo/a,Codigo Municipio
0,44001 Ababuj,30,35,*,*,*,44001
1,40001 Abades,390,400,*,*,80,40001
2,10001 Abadía,140,170,*,*,10,10001
3,27001 Abadín,965,1355,*,60,370,27001
4,48001 Abadiño,3165,3685,*,95,345,48001

In [7]:
ColNue = ['Codigo Municipio', 'Soltero/a', 'Casado/a', 'Separado/a', 'Divorciado/a', 'Viudo/a']
EstadoCivil11[ColNue]

     Codigo Municipio Soltero/a Casado/a Separado/a Divorciado/a Viudo/a
0               44001        30       35          *            *       *
1               40001       390      400          *            *      80
2               10001       140      170          *            *      10
3               27001       965     1355          *           60     370
4               48001      3165     3685          *           95     345
...               ...       ...      ...        ...          ...     ...
8111            20081      4325     4415          *          195     525
8112            20080      3895     4925        105          290     765
8113            09485        30       25          *            *       *
8114            31265        45       35          *            *      15
8115            04103       835     1980          *           70     160

[8116 rows x 6 columns]

In [8]:
EstadoCivil11.to_csv('19_Output_Estado_Civil_11.csv', header = True, index = False)