## Impuestos ayuntamientos 2011
En este notebook procesaremos un .xlsx con el total de impuestos que recauda cada municipio.  
Obtendremos un DataFrame con la siguiente información:
- Codigo Municipio
- Total impuestos (Millones euros)

In [1]:
import pandas as pd

In [2]:
Impuestos11 = pd.read_excel('33_Input_Impuestos_11.xlsx', dtype = {'Prov' : str,'Corp' : str}, 
                            usecols = ['Prov', 'Corp', 'Impuestos directos', 'Impuestos indirectos'])
Impuestos11.head()

  Prov Corp  Impuestos directos  Impuestos indirectos
0   01  000         886267000.0          1.139214e+09
1   02  000           4919060.0          3.865020e+06
2   03  000          17556390.0          1.955065e+07
3   04  000           7715560.0          6.742120e+06
4   05  000           1837060.0          1.903250e+06

Creamos el campo Codigo Municipio

In [3]:
Impuestos11['Codigo Municipio'] = Impuestos11['Prov'].map(str)+Impuestos11['Corp'].map(str)
Impuestos11.head()

  Prov Corp  Impuestos directos  Impuestos indirectos Codigo Municipio
0   01  000         886267000.0          1.139214e+09            01000
1   02  000           4919060.0          3.865020e+06            02000
2   03  000          17556390.0          1.955065e+07            03000
3   04  000           7715560.0          6.742120e+06            04000
4   05  000           1837060.0          1.903250e+06            05000

Creamos una única columna con la suma de los impuestos directos e indirectos y lo pasamos a Millones de euros

In [4]:
Impuestos11['Total impuestos (Miles de €)'] = (Impuestos11['Impuestos directos'] \
                                                   + Impuestos11['Impuestos indirectos'])/1000
Impuestos11.head()

,Prov,Corp,Impuestos directos,Impuestos indirectos,Codigo Municipio,Total impuestos (Miles de €)
0,01,000,886267000.0,1.139214e+09,01000,2025481.106
1,02,000,4919060.0,3.865020e+06,02000,8784.080
2,03,000,17556390.0,1.955065e+07,03000,37107.040
3,04,000,7715560.0,6.742120e+06,04000,14457.680
4,05,000,1837060.0,1.903250e+06,05000,3740.310

In [5]:
Impuestos11.drop(['Prov','Corp', 'Impuestos directos','Impuestos indirectos'], axis = 1, inplace = True)

PrimeraColumna = Impuestos11.pop('Codigo Municipio')
Impuestos11.insert(0,'Codigo Municipio', PrimeraColumna)

Impuestos11.head()

  Codigo Municipio  Total impuestos (Miles de €)
0            01000                   2025481.106
1            02000                      8784.080
2            03000                     37107.040
3            04000                     14457.680
4            05000                      3740.310

In [6]:
Impuestos11.to_csv('33_Output_Impuestos_11.csv', header = True, index = False)